/**
 * Regenerate the committed per-polygon country bbox table read by
 * `allCountryPolygonBboxes()` (chain scope resolution + microstate candidate
 * discovery). Needs the prepared CGAZ ADM0 dataset — run
 * `prepare-country-polygon-caches.ts` first on a host that lacks it.
 *
 * The table is committed rather than cached so scope resolution never depends
 * on the 95 MB boundary dataset being present; the output file name pins the
 * CGAZ release and simplification tolerance it was derived from.
 *
 * Run: `cd pipeline && npm run gen:country-polygon-bboxes` (then commit the diff).
 */

import { writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { deriveCountryPolygonBboxes } from './country-polygon.js'

const OUT = resolve(import.meta.dirname, 'country-polygon-bboxes-cgaz-v6-s0005.generated.json')

const bboxes = deriveCountryPolygonBboxes()
writeFileSync(OUT, `${JSON.stringify({
  _doc: 'Generated by pipeline/lib/gen-country-polygon-bboxes.ts — ISO2 → [s, w, n, e] per CGAZ ADM0 polygon part. Do not edit.',
  cgaz_release: 'geoBoundaries v6.0.0 CGAZ ADM0, ogr2ogr -simplify 0.0005',
  bboxes,
})}\n`)
console.log(`country-polygon bboxes: ${Object.keys(bboxes).length} countries → ${OUT}`)
