/**
 * Generate `engine/noise-compute/src/sources.rs` from `pipeline/lib/sources.ts`.
 *
 * Single source of truth for dataset metadata is the TypeScript registry.
 * This script produces the Rust mirror that the engine compiles in — no
 * `build.rs` → `npx tsx` chain (plan v5 /gg W: keep Rust builds pure Rust).
 *
 * Workflow: edit `sources.ts` → run `npm run gen:sources` (from pipeline/)
 * → commit both files together. Pre-commit hook may check the two stay in
 * sync.
 *
 * Usage:
 *   cd pipeline && npx tsx lib/gen-sources-rs.ts
 *   # or
 *   cd pipeline && npm run gen:sources
 */

import { readFileSync, writeFileSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import { SOURCES, type Provenance } from './sources.js'

const __dirname = dirname(fileURLToPath(import.meta.url))
const OUTPUT_PATH = resolve(__dirname, '../../engine/noise-compute/src/sources.rs')
const TS_OUTPUT_PATH = resolve(__dirname, 'source-ids.generated.ts')

/** Convert a source `key` into a SCREAMING_SNAKE TS / Rust identifier:
 *  `'cz-rsd-scitani'` → `'CZ_RSD_SCITANI'`. */
function keyToConstName(key: string): string {
  return key
    .replace(/[^A-Za-z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '')
    .toUpperCase()
}

const PROVENANCE_TO_RUST: Record<Provenance, string> = {
  'city-measured': 'Provenance::CityMeasured',
  'national-measured': 'Provenance::NationalMeasured',
  'continental-measured': 'Provenance::ContinentalMeasured',
  'global-measured': 'Provenance::GlobalMeasured',
  'national-proxy': 'Provenance::NationalProxy',
  'heuristic': 'Provenance::Heuristic',
  'baseline': 'Provenance::Baseline',
  'none': 'Provenance::None',
}

/** Serialise a string for a Rust string literal — JSON escaping matches Rust. */
function rustStr(s: string): string {
  return JSON.stringify(s)
}

function rustOptStr(s: string | null): string {
  return s === null ? 'None' : `Some(${rustStr(s)})`
}

function rustOptU16(n: number | null): string {
  return n === null ? 'None' : `Some(${n})`
}

const HEADER = `//! Generated by \`pipeline/lib/gen-sources-rs.ts\` — DO NOT EDIT MANUALLY.
//!
//! Rust mirror of \`pipeline/lib/sources.ts\`. Regenerate via:
//!
//! \`\`\`bash
//! cd pipeline && npm run gen:sources
//! \`\`\`
//!
//! This file is committed to git (no \`build.rs\` / node dependency in the
//! Rust build — plan v5 /gg W: keep noise-compute a pure-Rust crate).

use serde::{Deserialize, Serialize};

/// How authoritative a dataset is. Must stay aligned with the TypeScript
/// \`Provenance\` union in \`pipeline/lib/sources.ts\`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum Provenance {
    #[serde(rename = "city-measured")]
    CityMeasured,
    #[serde(rename = "national-measured")]
    NationalMeasured,
    #[serde(rename = "continental-measured")]
    ContinentalMeasured,
    #[serde(rename = "global-measured")]
    GlobalMeasured,
    #[serde(rename = "national-proxy")]
    NationalProxy,
    #[serde(rename = "heuristic")]
    Heuristic,
    #[serde(rename = "baseline")]
    Baseline,
    #[serde(rename = "none")]
    None,
}

impl Provenance {
    /// Ranking for overwrite decisions. Higher wins. Mirrors
    /// \`pipeline/lib/sources.ts::PROVENANCE_RANK\`.
    pub fn rank(self) -> u8 {
        match self {
            Self::CityMeasured => 7,
            Self::NationalMeasured => 6,
            Self::ContinentalMeasured => 5,
            Self::GlobalMeasured => 4,
            Self::NationalProxy => 3,
            Self::Heuristic => 2,
            Self::Baseline => 1,
            Self::None => 0,
        }
    }

    /// Stable string form for logging and JSON — matches the TypeScript union.
    pub fn as_str(self) -> &'static str {
        match self {
            Self::CityMeasured => "city-measured",
            Self::NationalMeasured => "national-measured",
            Self::ContinentalMeasured => "continental-measured",
            Self::GlobalMeasured => "global-measured",
            Self::NationalProxy => "national-proxy",
            Self::Heuristic => "heuristic",
            Self::Baseline => "baseline",
            Self::None => "none",
        }
    }

    /// True if this source represents real measured data (any measured tier —
    /// city, national, continental or global-scale observational). Used by
    /// \`access_factor\` to pass measured AADT through without re-applying access
    /// multipliers (a real count already reflects the restriction). Deliberately
    /// EXCLUDES \`NationalProxy\`: a class-default estimate does NOT reflect the
    /// restriction, so the engine must still down-scale it on private / farm /
    /// forestry roads (gg 2026-06-14, Ondra's call).
    pub fn is_measured(self) -> bool {
        matches!(
            self,
            Self::CityMeasured
                | Self::NationalMeasured
                | Self::ContinentalMeasured
                | Self::GlobalMeasured
        )
    }

    /// True if the row carries any enricher-written data (anything except
    /// the \`None\` sentinel). Equivalent to the legacy \`traffic_source > 0\`
    /// check, derivable from \`dataset_id\` via \`provenance_of()\`.
    pub fn has_data(self) -> bool {
        !matches!(self, Self::None)
    }

    /// Legacy string form for the JSON API contract
    /// (\`frontend/src/types/noise.ts::traffic_source\` union). Folds the six
    /// Provenance variants into the three strings the frontend currently
    /// understands. When F.4 lands (ts-rs derivation), the frontend will
    /// switch to the full \`as_str()\` form and this helper goes away.
    pub fn legacy_traffic_source_str(self) -> &'static str {
        match self {
            // NationalProxy folds in here so the popup still shows its dataset
            // attribution; the coarse 3-bucket label can't say "estimate" yet
            // (F.4 as_str() will). The acoustic distinction lives in is_measured().
            Self::CityMeasured
            | Self::NationalMeasured
            | Self::ContinentalMeasured
            | Self::GlobalMeasured
            | Self::NationalProxy => "matched_external",
            Self::Heuristic => "estimated_service_tree",
            Self::Baseline | Self::None => "default_by_class",
        }
    }
}

/// One enrichment dataset. Mirrors the TypeScript \`Source\` interface.
#[derive(Debug, Clone, Copy)]
pub struct Source {
    pub id: u16,
    pub key: &'static str,
    pub provenance: Provenance,
    pub layer: &'static str,
    pub name: &'static str,
    pub license: Option<&'static str>,
    pub url: Option<&'static str>,
    pub year: Option<u16>,
}

impl Source {
    /// Sentinel "unspecified" entry used for pre-provenance rows (id = 0).
    pub const UNSPECIFIED: Source = SOURCES[0];
}

/// Fixed source id for the single aircraft observational dataset
/// (\`global-adsb-planet\`). Avoids scattering the magic literal \`1\`
/// across every aircraft writer / reader.
pub const AIRCRAFT_ADSB_SOURCE_ID: u16 = 1;

/// Binary search by id — SOURCES is emitted sorted by id (generator
/// preserves TS \`DATASETS\` order, which is id-ascending). Called per
/// road / rail / industrial row in tile-painter + source-reader hot
/// paths, so O(log N) beats the previous O(N).
pub fn get_source(id: u16) -> Option<&'static Source> {
    SOURCES
        .binary_search_by_key(&id, |s| s.id)
        .ok()
        .map(|idx| &SOURCES[idx])
}

/// Shorthand for the common "what's the provenance of this stamp" lookup.
pub fn provenance_of(id: u16) -> Provenance {
    get_source(id).map_or(Provenance::None, |s| s.provenance)
}

/// Compact dataset attribution attached to popup contributors and
/// segments. Mirrors the TS \`lookupProvenance\` shape so the wire JSON
/// stays unchanged — previously assembled server-side in Node from a
/// duplicate \`SOURCES_BY_ID\` map. Moved into Rust because (a) the
/// generator already mirrors \`SOURCES\` here so there is one source of
/// truth, and (b) the Node enrichment was a no-op since the field
/// rename \`dataset_id\` → \`source_id\` (provenance came out \`null\` on
/// every popup).
#[derive(Debug, Clone, Copy, serde::Serialize)]
pub struct DatasetMeta {
    pub name: &'static str,
    pub year: Option<u16>,
    pub license: Option<&'static str>,
    pub url: Option<&'static str>,
    /// Provenance tier of this dataset, forwarded verbatim so the popup UI can
    /// label measured vs national-proxy without re-deriving from a second
    /// registry (the Node/Rust split moved DatasetMeta into Rust for exactly
    /// this — 0db-codex ProvenanceTier consumer). Wire = the serde-rename
    /// kebab (\`"national-measured"\`, \`"national-proxy"\`, …).
    pub tier: Provenance,
}

/// \`dataset_meta(id)\` returns the wire-shape \`DatasetMeta { name, year,
/// license, url, tier }\` used for popup display. \`None\` for id 0 / unknown
/// ids — the popup then renders its per-kind fallback line.
pub fn dataset_meta(id: u16) -> Option<DatasetMeta> {
    if id == 0 {
        return None; // sentinel row exists in SOURCES but is not a dataset
    }
    get_source(id).map(|s| DatasetMeta {
        name: s.name,
        year: s.year,
        license: s.license,
        url: s.url,
        tier: s.provenance,
    })
}
`

// Defence in depth — `get_source` in Rust uses binary_search_by_key, which
// requires the emitted array to be sorted by id. We sort here so a
// developer grouping new entries by country / layer in enrichment-datasets.ts
// can't silently break the lookup.
const sortedSources = [...SOURCES].sort((a, b) => a.id - b.id)
const entries = sortedSources.map((s) => {
  return `    Source {
        id: ${s.id},
        key: ${rustStr(s.key)},
        provenance: ${PROVENANCE_TO_RUST[s.provenance]},
        layer: ${rustStr(s.layer)},
        name: ${rustStr(s.name)},
        license: ${rustOptStr(s.license)},
        url: ${rustOptStr(s.url)},
        year: ${rustOptU16(s.year)},
    },`
}).join('\n')

// Tests come AFTER pub const SOURCES so clippy::items_after_test_module doesn't fire.
const output = `${HEADER}
pub const SOURCES: &[Source] = &[
${entries}
];

#[cfg(test)]
mod sources_tests {
    use crate::sources::{get_source, provenance_of, Provenance, Source, SOURCES};

    #[test]
    fn unspecified_is_id_zero_sentinel() {
        let s = &SOURCES[0];
        assert_eq!(s.id, 0);
        assert_eq!(s.key, "unspecified");
        assert_eq!(s.provenance, Provenance::None);
        assert_eq!(Source::UNSPECIFIED.id, 0);
    }

    #[test]
    fn dataset_meta_zero_is_none() {
        assert!(crate::sources::dataset_meta(0).is_none());
        assert!(crate::sources::dataset_meta(20).is_some()); // cz-rsd
    }

    #[test]
    fn dataset_meta_tier_serializes() {
        // The popup UI (0db-codex ProvenanceTier) reads DatasetMeta.tier to
        // label measured vs national-proxy. Pin the wire strings so a rename
        // can't silently break the consumer: id 20 = national-measured,
        // 1013/2037 = national-proxy.
        let m20 = crate::sources::dataset_meta(20).unwrap(); // cz-rsd-scitani
        assert_eq!(m20.tier, Provenance::NationalMeasured);
        assert_eq!(
            serde_json::to_value(m20).unwrap()["tier"],
            "national-measured"
        );
        for proxy in [1013u16, 2037, 9870, 9871, 9872, 9873, 9874, 9875, 9876] {
            // Existing road/rail proxies and row-level classification fallbacks.
            let m = crate::sources::dataset_meta(proxy).unwrap();
            assert_eq!(m.tier, Provenance::NationalProxy);
            assert_eq!(serde_json::to_value(m).unwrap()["tier"], "national-proxy");
        }
    }

    #[test]
    fn no_duplicate_ids() {
        let mut seen = std::collections::HashSet::new();
        for s in SOURCES {
            assert!(seen.insert(s.id), "duplicate id={} (key={})", s.id, s.key);
        }
    }

    #[test]
    fn no_duplicate_keys() {
        let mut seen = std::collections::HashSet::new();
        for s in SOURCES {
            assert!(seen.insert(s.key), "duplicate key={} (id={})", s.key, s.id);
        }
    }

    #[test]
    fn provenance_rank_monotonic() {
        assert!(Provenance::CityMeasured.rank() > Provenance::NationalMeasured.rank());
        assert!(Provenance::NationalMeasured.rank() > Provenance::ContinentalMeasured.rank());
        assert!(Provenance::ContinentalMeasured.rank() > Provenance::GlobalMeasured.rank());
        assert!(Provenance::GlobalMeasured.rank() > Provenance::NationalProxy.rank());
        assert!(Provenance::NationalProxy.rank() > Provenance::Heuristic.rank());
        assert!(Provenance::Heuristic.rank() > Provenance::Baseline.rank());
        assert!(Provenance::Baseline.rank() > Provenance::None.rank());
    }

    #[test]
    fn get_source_looks_up_by_id() {
        let rsd = get_source(20).expect("cz-rsd (id=20) must exist");
        assert_eq!(rsd.key, "cz-rsd-scitani");
        assert_eq!(rsd.provenance, Provenance::NationalMeasured);
    }

    #[test]
    fn provenance_of_unknown_id_is_none() {
        assert_eq!(provenance_of(0), Provenance::None);
        assert_eq!(provenance_of(u16::MAX), Provenance::None);
    }

    #[test]
    fn sources_sorted_by_id_for_binary_search() {
        // get_source uses binary_search_by_key; the generator emits SOURCES
        // in id-ascending order. Lock the invariant so a hand-edit to
        // sources.rs (or a reordered DATASETS) can't silently break lookup.
        for pair in SOURCES.windows(2) {
            assert!(
                pair[0].id < pair[1].id,
                "SOURCES not sorted by id: {} then {}",
                pair[0].id,
                pair[1].id
            );
        }
    }
}
`

// ── TypeScript per-source-id constants ────────────────────────────────────
//
// Enrichers that previously did `SOURCE_ID_CZ_RSD_SCITANI`
// import a typed constant instead, so a key rename is a compile-time error
// instead of a runtime crash.

const tsLines: string[] = [
  '// AUTO-GENERATED — DO NOT EDIT.',
  '//',
  '// Per-source-id constants emitted from `pipeline/lib/sources.ts` by',
  '// `pipeline/lib/gen-sources-rs.ts`. Re-run via `npm run gen:sources`',
  '// (from `pipeline/`) and commit both this file and `sources.rs`.',
  '',
]

// Detect duplicate ids / clashing const names eagerly — the registry rules
// enforce id uniqueness, but a typo in two source keys could collapse to
// the same identifier and trip a compile error downstream.
const namesSeen = new Map<string, string>()
for (const s of sortedSources) {
  const name = `SOURCE_ID_${keyToConstName(s.key)}`
  const dup = namesSeen.get(name)
  if (dup !== undefined) {
    console.error(
      `ERROR: duplicate constant name ${name} for keys '${s.key}' vs '${dup}'`,
    )
    process.exit(1)
  }
  namesSeen.set(name, s.key)
  tsLines.push(`export const ${name} = ${s.id} as const // ${s.key}`)
}
tsLines.push('')

const tsOutput = tsLines.join('\n')
const artifacts = [
  { path: OUTPUT_PATH, contents: output },
  { path: TS_OUTPUT_PATH, contents: tsOutput },
]

const args = process.argv.slice(2)
if (args.some(arg => arg !== '--check')) {
  throw new Error(`usage: gen-sources-rs.ts [--check]`)
}
if (args.includes('--check')) {
  const stale = artifacts.filter(artifact => {
    try { return readFileSync(artifact.path, 'utf8') !== artifact.contents }
    catch { return true }
  })
  if (stale.length > 0) {
    throw new Error(`generated source registry is stale: ${stale.map(artifact => artifact.path).join(', ')}`)
  }
  console.log(`✓ Generated source registry is current (${SOURCES.length} entries).`)
} else {
  for (const artifact of artifacts) writeFileSync(artifact.path, artifact.contents)
  console.log(`✓ Generated Rust and TypeScript source registries with ${SOURCES.length} entries.`)
}
