/** Generated by pipeline/generate-road-planning-defaults.ts; edit authoritative engine tables. */

export const WORLD_DEFAULT = [[21600,2400,5700,300],[11700,1200,1800,300],[7470,540,810,180],[2640,120,180,60],[720,26,38,16],[480,5,10,5],[98,0,1,1],[240,2,5,3],[4,0,1,0],[1200,30,80,30],[3240,360,855,45],[1755,180,270,45],[1120.5,81,121.5,27]] as const
export const LEGACY_SPEED = [100,70,50,50,50,30,20,20,20,50,60,50,50] as const
export const CZ_SPEEDS = [50,90,130,110] as const
export const GDP_SCALED_CLASSES = [0,1,2,10,11,12] as const
export const DERESTRICTED_SPEED_KMH = 130
