/**
 * Unified provenance registry — single source of truth for noise-dataset
 * provenance across roads, railways, buildings, industrial and aircraft.
 * Layers a `Provenance` classification on top of the legacy `DATASETS`
 * array from `enrichment-datasets.ts`. The Rust mirror at
 * `engine/noise-compute/src/sources.rs` is generated by
 * `scripts/gen-sources-rs.ts` and committed alongside this file.
 *
 * Overwrite semantics (`shouldOverwrite`):
 *   - `Provenance` rank drives the decision (measured > heuristic >
 *     baseline) so engine and pipeline can branch on it without a
 *     per-segment registry lookup.
 *   - Tie-break on equal rank: newer `year` wins, then higher `id` as a
 *     deterministic last resort.
 *   - `existingId === selfId` → overwrite, so an enricher re-run is
 *     idempotent.
 */

import { DATASETS, type Dataset, type Provenance } from './enrichment-datasets.js'

// Provenance enum + rank

/**
 * How authoritative the data is. (The `Provenance` TYPE lives in
 * `enrichment-datasets.ts` — upstream of this module — so a dataset entry can
 * DECLARE its tier; it is re-exported here, the historical import site.)
 *
 * - `city-measured` — per-segment match against a municipal traffic counter
 *   inside a city polygon; denser/newer than the national census it overrides.
 *   - `national-measured`     — per-segment spatial or ref match against a
 *                               national authority's published measurement
 *                               (ŘSD, BASt, MITMA, DNIT, FHWA HPMS, DOH, …).
 *   - `continental-measured`  — per-segment harmonised measurement across
 *                               multiple countries (EU CityTraffic, E-PRTR,
 *                               continental GTFS).
 *   - `global-measured`       — per-facility observational dataset with
 *                               global reach (GPPD power plants, USWTDB
 *                               wind turbines, ADS-B aircraft).
 *   - `national-proxy`        — national-scale ESTIMATE, not a measurement:
 *                               class/corridor-default AADT or trains/day
 *                               anchored to real national context (city tiers,
 *                               known freight lines). Outranks OSM defaults so
 *                               it enriches its own country, but is NOT measured
 *                               — it can't overwrite a real measured neighbour
 *                               and the engine still applies `access_factor`.
 *   - `heuristic`             — model-computed estimate (service-tree flow
 *                               accumulation, NACE name-keyword match).
 *   - `baseline`              — OSM-only inference or global baseline
 *                               coverage (Overture buildings, Copernicus
 *                               DEM, OSM tag-only fallback, R7 taper).
 *   - `none`                  — sentinel for unenriched rows (id = 0).
 */
export type { Provenance }

/**
 * Lexicographic rank for `shouldOverwrite`. Higher rank wins.
 *
 * Tiers roughly mirror the legacy `priority` scale (80/70/50/10/0) but use
 * an enum so engine code can branch cleanly (measured → skip access_factor;
 * heuristic → apply access_factor; none → engine-side default cascade).
 */
export const PROVENANCE_RANK: Record<Provenance, number> = {
  // Municipal counters beat national census INSIDE the city polygon: they
  // cover the same streets plus locals with denser, newer measurements;
  // polygon and coverage gates protect the rank.
  'city-measured': 7,
  'national-measured': 6,
  'continental-measured': 5,
  'global-measured': 4,
  // national-proxy sits BELOW every real measured tier (a proxy can never
  // overwrite a measured neighbour) but ABOVE heuristic/baseline (it still
  // enriches OSM defaults inside its own country).
  'national-proxy': 3,
  'heuristic': 2,
  'baseline': 1,
  'none': 0,
}

// Source interface + registry

export interface Source {
  id: number            // u16, globally unique, never recycled
  key: string           // stable slug ('cz-rsd', 'br-dnit', ...)
  provenance: Provenance
  layer: Dataset['layer']  // roads | railways | buildings | industrial | any
  name: string
  license: string | null
  url: string | null
  year: number | null   // used for same-rank tiebreak (newer wins)
  /** Single-country ownership (see `isNationallyOwnedSource`): true for the
   *  city/national provenance tiers by construction, plus any entry the
   *  registry explicitly flags `nationallyOwned` (cz-timetable-silent —
   *  baseline tier, still CZ-only testimony). */
  nationallyOwned: boolean
}

/**
 * Derive a `Provenance` label: an entry's own `provenance` declaration wins
 * (Overture/Copernicus baselines, R7 taper), otherwise the legacy `priority`
 * ladder decides.
 *
 * Mapping:
 *   priority 90 → city-measured (municipal counters)
 *   priority 80 → national-measured, EXCEPT measurement:'proxy' → national-proxy
 *                 (a national-scale estimate, not a real count — see Provenance)
 *   priority 70 → continental-measured
 *   priority 50 → global-measured
 *   priority 10 → heuristic
 *   priority 0  → none (sentinel)
 *   other       → none (defensive for malformed entries)
 *
 * Keep this function deterministic — it is exercised by the Rust codegen
 * script (`gen-sources-rs.ts`) and by the `shouldOverwrite` tiebreak path.
 */
export function provenanceFromEntry(d: Dataset): Provenance {
  if (d.id === 0) return 'none'
  if (d.provenance) return d.provenance
  if (d.priority >= 90) return 'city-measured'
  // A proxy at national priority is an estimate, not a measurement: drop it to a
  // dedicated non-measured tier so the engine re-applies access_factor and it can
  // never overwrite a real measured neighbour (gg 2026-06-14, Ondra's call).
  if (d.priority >= 80) return d.measurement === 'proxy' ? 'national-proxy' : 'national-measured'
  if (d.priority >= 70) return 'continental-measured'
  if (d.priority >= 50) return 'global-measured'
  if (d.priority >= 10) return 'heuristic'
  return 'none'
}

/** Provenance tiers that imply single-country ownership by construction — a
 *  municipal counter or national census/timetable speaks for exactly one
 *  country's territory. Continental/global tiers are multi-country by
 *  definition; heuristic/baseline tiers are owner-neutral UNLESS the registry
 *  entry itself declares `nationallyOwned` (cz-timetable-silent). */
const NATIONALLY_OWNED_PROVENANCE_TIERS: ReadonlySet<Provenance> =
  new Set(['city-measured', 'national-measured', 'national-proxy'])

/** The unified SOURCES array — one entry per dataset, with derived provenance. */
export const SOURCES: readonly Source[] = DATASETS.map<Source>((d) => {
  const provenance = provenanceFromEntry(d)
  return {
    id: d.id,
    key: d.key,
    provenance,
    layer: d.layer,
    name: d.name,
    license: d.license,
    url: d.url,
    year: d.year,
    nationallyOwned: NATIONALLY_OWNED_PROVENANCE_TIERS.has(provenance) || d.nationallyOwned === true,
  }
})

export const SOURCES_BY_ID = new Map<number, Source>(SOURCES.map((s) => [s.id, s]))
export const SOURCES_BY_KEY = new Map<string, Source>(SOURCES.map((s) => [s.key, s]))

/** Single-country source keys that predate or deliberately omit the `cc-…` convention. */
const COUNTRY_BY_NONSTANDARD_SOURCE = new Map<string, string>([
  ['city-praha-tsk', 'CZ'],
  ['city-wien-dauerzaehlstellen', 'AT'],
  ['city-brno-detectors', 'CZ'],
  ['global-uswtdb', 'US'],
])

/** Extra ISO territories legitimately covered by a country's national network. */
const NATIONAL_SOURCE_TERRITORY_EXTENSIONS = new Map<string, readonly string[]>([
  ['MA', ['EH']],
])

/** ISO2 owner for a single-country source, or null for a world/continental source.
 * A newly registered single-country source without an owner fails loudly here;
 * enrichment must never guess that it may write across a border. */
export function countryIsoForNationalSource(id: number): string | null {
  const source = SOURCES_BY_ID.get(id)
  if (!source?.nationallyOwned) return null
  const country = COUNTRY_BY_NONSTANDARD_SOURCE.get(source.key) ?? /^([a-z]{2})-/.exec(source.key)?.[1]?.toUpperCase()
  if (!country) throw new Error(`nationally owned source '${source.key}' has no ISO2 owner`)
  return country
}

/** ISO territories owned by one country's national inputs. */
export function countryOwnershipIsos(country: string): readonly string[] {
  return [country, ...(NATIONAL_SOURCE_TERRITORY_EXTENSIONS.get(country) ?? [])]
}

/** Baked ISO owners accepted for a single-country source, including declared territories. */
export function countryIsosForNationalSource(id: number): readonly string[] | null {
  const country = countryIsoForNationalSource(id)
  return country === null
    ? null
    : countryOwnershipIsos(country)
}

/** The sentinel "unspecified" entry (always id = 0). */
export const UNSPECIFIED: Source = SOURCES_BY_ID.get(0)!

/**
 * True if `id` carries REAL measured data — TS mirror of Rust
 * `Provenance::is_measured` (`engine/noise-compute/src/sources.rs`): any of the
 * four measured tiers (city/national/continental/global), which is exactly
 * `PROVENANCE_RANK >= global-measured`. Deliberately EXCLUDES `national-proxy`
 * (a class-default estimate), `heuristic` (service-tree / continuity-fill self)
 * and `baseline`. The continuity-fill uses it to pick anchors it may propagate
 * from — only hard measurements anchor, never another heuristic (so re-runs
 * can't chain off their own output).
 */
export function isMeasured(id: number): boolean {
  const s = SOURCES_BY_ID.get(id)
  return s ? PROVENANCE_RANK[s.provenance] >= PROVENANCE_RANK['global-measured'] : false
}

/**
 * True when `id` is a SINGLE-COUNTRY-owned source: the city/national
 * provenance tiers (a municipal counter / national census / national
 * timetable testifies about exactly one country) plus any registry entry
 * explicitly flagged `nationallyOwned` (cz-timetable-silent — baseline tier,
 * still CZ-only testimony). Unknown/sentinel ids are NOT nationally owned.
 *
 * Consumer: the rail-walk driver's foreign-national stamp guard
 * (`rail-walk-enrich.ts`, DE Step A v2 Codex review item 4, 2026-07-16) —
 * a walk must never overwrite ANOTHER country's national data, even where
 * `shouldOverwrite`'s rank/year ladder alone would allow it (verified live:
 * DE 9864 vs CZ 110 is a same-rank newer-year win, and CZ prepared data is
 * FINAL). Territory, not rank, is the boundary between two national feeds.
 */
export function isNationallyOwnedSource(id: number): boolean {
  return SOURCES_BY_ID.get(id)?.nationallyOwned === true
}

// Overwrite decision

/**
 * Returns `true` if a write stamped by `newId` should replace the row's
 * current `existingId`.
 *
 * Rules (in priority order):
 *   1. Empty slot (existing = 0) → overwrite
 *   2. Idempotent re-run (existing = self) → overwrite (safe — same source)
 *   3. Unknown id in registry → overwrite (defensive: treat as legacy)
 *   4. Higher provenance rank wins
 *   5. Same rank: newer `year` wins
 *   6. Same rank + same year (or any null): higher id wins (deterministic)
 *
 * (Plan v5 /gg Gemini C2 idempotent early return; DeepSeek W3 year before id.)
 */
export function shouldOverwrite(existingId: number, newId: number): boolean {
  if (existingId === 0 || existingId === newId) return true
  const a = SOURCES_BY_ID.get(existingId)
  const b = SOURCES_BY_ID.get(newId)
  if (!a || !b) return true
  const rA = PROVENANCE_RANK[a.provenance]
  const rB = PROVENANCE_RANK[b.provenance]
  if (rB !== rA) return rB > rA
  if (a.year !== null && b.year !== null && a.year !== b.year) return b.year > a.year
  return b.id > a.id
}

// Re-export the per-source-id constants generated by `gen-sources-rs.ts`.
// Enrichers can now write the named constant rather than the runtime
// `SOURCES_BY_KEY` lookup — a key rename becomes a compile error instead
// of a silent runtime crash. Same generator emits the Rust mirror.
export * from './source-ids.generated.js'
