//! NPD lookup tables, profile metadata, reach estimation.
//!
//! `NpdProfile` carries per-typecode SEL/LAmax curves from EASA ANP v2.3
//! (auto-generated by `scripts/build-aircraft-profiles.py`). `NpdLuts`
//! pre-computes 128-bin log-distance interpolators per noise class for
//! the popup and pipeline hot paths.

use std::sync::{LazyLock, OnceLock};

/// NPD SEL threshold for per-profile reach calculation.
/// At this raw NPD SEL, a segment's contribution is negligible (< 0.15 dB on total Lden).
pub const AIRCRAFT_NPD_REACH_THRESHOLD_DB: f64 = 40.0;

/// Hard cap on per-profile **slant** reach (meters). Used by
/// `Profile::estimate_reach_m` to bound the bisection in the physics
/// tail and by the per-segment slant-vs-reach test inside the
/// pipeline scatter and popup compute paths. With the physics tail
/// (`alpha_eff`), jets stay above 40 dB SEL out to ~15.5 km slant.
/// Numerically equal to `AIRCRAFT_MAX_HORIZONTAL_REACH_M` because at
/// altitude 0 horizontal = slant, but they're conceptually different —
/// callers should pick the constant that matches the geometry they're
/// filtering on.
pub const AIRCRAFT_NPD_REACH_CAP_M: f64 = 16_000.0;

/// Hard cap on **horizontal** distance (meters) at which an airborne
/// segment can be audible at 40 dB SEL, regardless of altitude. Used
/// by `source-reader` r-tree query envelopes and any other prefilter
/// operating on horizontal distance. For altitudes above 0 the actual
/// horizontal reach is bounded by `sqrt(slant_cap² − alt²)`, so this
/// constant is the upper envelope — safe to use for prefilters, but
/// the per-profile slant test inside the kernel does the exact
/// rejection.
pub const AIRCRAFT_MAX_HORIZONTAL_REACH_M: f64 = 16_000.0;

/// Maximum z15 cell diagonal in the Doc 29 projection (at the equator).
pub const CRUISE_CELL_DIAGONAL_EQUATOR_M: f64 = 360.0 / grid::cruise::CRUISE_AXIS as f64
    * super::doc29::M_PER_DEG_LAT
    * std::f64::consts::SQRT_2;

/// A cell-local representative segment can extend half a cell diagonal toward a receiver.
pub const CRUISE_QUERY_RADIUS_M: f64 =
    AIRCRAFT_MAX_HORIZONTAL_REACH_M + CRUISE_CELL_DIAGONAL_EQUATOR_M / 2.0;

/// Longest airborne sub-segment row a prepared `airborne.arrow` may hold. The
/// shuffle splits a longer chord (a 120 s coverage gap yields 18 km) into
/// `ceil(length / cap)` equal pieces, each owned by its midpoint square, so the
/// popup's owner-square pad is this constant and never the longest chord in a
/// file. Splitting only changes the Doc 29 finite-segment terms (|ΔLden| ≤
/// 0.01 dB per layer on the reference points) and draws one polyline instead
/// of one line.
pub const AIRBORNE_SUB_SEGMENT_MAX_LENGTH_M: f32 = 4_000.0;

/// Horizontal radius within which a stored airborne sub-segment can reach a
/// receiver: a row is owned by its midpoint square and extends at most half
/// the length cap from that midpoint.
pub const AIRBORNE_QUERY_RADIUS_M: f64 =
    AIRCRAFT_MAX_HORIZONTAL_REACH_M + AIRBORNE_SUB_SEGMENT_MAX_LENGTH_M as f64 / 2.0;

/// Reference slant (meters) at the last NPD table point (25 000 ft). Anchor
/// for physics-based extrapolation of SEL beyond the table.
pub const AIRCRAFT_NPD_REF_SLANT_M: f64 = 7620.0;

/// Standard NPD distances in feet (Doc 29 §4.2, 10 points).
const NPD_DIST_FT: [f64; 10] = [
    200.0, 400.0, 630.0, 1000.0, 2000.0, 4000.0, 6310.0, 10000.0, 16000.0, 25000.0,
];

/// Pre-computed log10 of standard distances.
const LOG_DIST: [f64; 10] = [
    2.30103, 2.60206, 2.79934, 3.0, 3.30103, 3.60206, 3.79934, 4.0, 4.20412, 4.39794,
];

pub const FT_PER_M: f64 = 3.28084;

/// Engine installation type determines ΔI coefficients.
#[derive(Clone, Copy, PartialEq, Debug)]
pub enum Installation {
    /// Wing-mounted turbofan: a=0.0039, b=0.062, c=0.8786
    Wing,
    /// Fuselage/tail-mounted: a=0.1225, b=0.329, c=1.0
    Fuselage,
    /// Propeller aircraft: ΔI = 0
    Propeller,
}

/// NPD profile definition.
///
/// SEL and LAmax NPD curves both come from EASA ANP v2.3 (the same
/// `ANP2.3_NPD_data.csv` file with rows tagged "SEL" or "LAmax"). The
/// generator ingests both; the kernel uses SEL for energy summation and
/// LAmax for per-event peak ranking.
pub struct NpdProfile {
    pub name: &'static str,
    pub approach_sel: [f64; 10],
    pub departure_sel: [f64; 10],
    /// LAmax NPD — peak A-weighted SPL per Doc 29 distance row.
    /// Replaces hardcoded `SEL − 12 dB` approximation that ignored
    /// per-aircraft Lmax/SEL differences (range 8–18 dB across operations).
    pub approach_lmax: [f64; 10],
    pub departure_lmax: [f64; 10],
    pub v_ref_kt: f64,
    pub installation: Installation,
    /// **NPD-tail residual coefficient** (dB/m), lazily back-fitted from the
    /// last three NPD points (see `compute_alpha_eff`). NOT a generic
    /// atmospheric-absorption value — it is the slope that, when paired
    /// with the `−20·log10(d/d_ref)` term in `interpolate_sel_logd`,
    /// reproduces the observed NPD curve through (10 k, 16 k, 25 k) ft.
    /// In effect it absorbs *both* atmospheric absorption *and* any
    /// residual divergence mismatch between Doc 29 NPD's empirical SEL
    /// slope and the spherical-spreading anchor — so the numerical value
    /// (jets ≈ 0.8–1.1 dB/km) is in the same ballpark as ISO 9613-1
    /// broadband α for typical aircraft spectra at standard atmosphere,
    /// but they are not interchangeable: swapping in an external ISO
    /// 9613-1 α (or scaling by a real atmosphere profile) will give
    /// wrong SEL because the divergence term double-counts. Stored
    /// per-direction because departure SEL tables drop faster than
    /// approach in the tail for most profiles.
    alpha_eff_approach: OnceLock<f64>,
    alpha_eff_departure: OnceLock<f64>,
}

impl NpdProfile {
    /// Const constructor used by `profiles_generated.rs` (sibling module of
    /// `emission`) to build the static `PROFILES` array. The two `OnceLock`
    /// fields stay private to this module; the generator can't construct
    /// them directly across module boundaries, so this fn is the bridge.
    pub const fn new(
        name: &'static str,
        approach_sel: [f64; 10],
        departure_sel: [f64; 10],
        approach_lmax: [f64; 10],
        departure_lmax: [f64; 10],
        v_ref_kt: f64,
        installation: Installation,
    ) -> Self {
        NpdProfile {
            name,
            approach_sel,
            departure_sel,
            approach_lmax,
            departure_lmax,
            v_ref_kt,
            installation,
            alpha_eff_approach: OnceLock::new(),
            alpha_eff_departure: OnceLock::new(),
        }
    }
}

mod scaled_distance;
pub use scaled_distance::build_scaled_distance_lut;

// Per-typecode NPD profiles + per-class metadata (constants in
// `profiles_generated.rs`) auto-generated from
// EASA ANP v2.3 + global traffic counts by
// `scripts/build-aircraft-profiles.py`. Classes are Voronoi-assigned
// over per-Installation anchor profiles (see generator docstring).
pub use crate::emission::profiles_generated::{
    is_negligible_noise_typecode, is_non_aircraft_typecode, noise_class_of, profile_idx,
    CLASS_NAMES, CLASS_OF_PROFILE, CLASS_REP_PROFILE_IDX, FALLBACK_NOISE_CLASS,
    FALLBACK_PROFILE_IDX, IS_JET, NUM_CLASSES, NUM_PROFILES,
    PROFILES,
};

/// Defensive clamp for `profile_idx` before indexing `PROFILES` /
/// `NpdLuts`. Generator guarantees `profile_idx < NUM_PROFILES` for any
/// typecode it emitted; this guard catches out-of-band data without
/// panicking.
#[inline]
pub fn clamp_profile_idx(profile_idx: u8) -> usize {
    (profile_idx as usize).min(NUM_PROFILES - 1)
}

/// True if `profile_idx` maps to the HELICOPTER noise class. Routes
/// through `CLASS_NAMES[noise_class]` rather than a hardcoded class
/// index because the generator orders classes by total traffic — the
/// helicopter index can shuffle on data updates.
#[inline]
pub fn is_helicopter_profile(profile_idx: u8) -> bool {
    let cls = noise_class_of(profile_idx) as usize;
    cls < CLASS_NAMES.len() && CLASS_NAMES[cls] == "HELICOPTER"
}

/// ICAO typecode prefix of a `PROFILES[idx].name`. Profile names are
/// stored as `"<icao_typecode>/<anp_designator>"` (e.g. `"B738/737800"`,
/// `"EMJ/EMB145"`) by the generator so the original ANP source is
/// traceable. The popup display only wants the 3-or-4-char ICAO
/// typecode prefix — naive 4-byte slicing would emit `"EMJ/"` for
/// 3-char codes. Returns `&'static str` so callers can dodge a
/// `String` allocation in tight loops.
///
/// `profile_idx` is clamped at usize-precision; downcasting to u8
/// first (`clamp_profile_idx(idx as u8)`) would silently fold every
/// `idx ≥ 256` to `idx & 0xFF`, then clamp to NUM_PROFILES-1 — fine
/// today (NUM_PROFILES = 124, so casting truncates at 256 anyway)
/// but a footgun if NUM_PROFILES ever grows.
pub fn profile_typecode(profile_idx: usize) -> &'static str {
    let idx = profile_idx.min(NUM_PROFILES - 1);
    let name = PROFILES[idx].name;
    name.split('/').next().unwrap_or(name)
}

/// Decode an ICAO typecode stored as `FixedSizeBinary(4)` (ASCII,
/// '\0'-padded — Stage 1's storage form) to a normal `String`. ICAO
/// typecodes are 3-4 chars (e.g. "B738", "A320", "CRJ"); the trim
/// drops the NUL pad. Invalid UTF-8 falls back to a lossy decode so
/// the popup never panics on malformed extract data.
pub fn typecode_to_string(bytes: &[u8; 4]) -> String {
    let end = bytes.iter().position(|&b| b == 0).unwrap_or(4);
    String::from_utf8_lossy(&bytes[..end]).into_owned()
}

/// Whether a profile's noise class is jet-classed. Routes through
/// `IS_JET[noise_class]` so the predicate stays correct as the generator
/// adds/reorders profiles. Used by airborne data-quality filters
/// (jet-stall, jet-low-AGL).
#[inline]
pub fn is_jet_profile(profile_idx: u8) -> bool {
    IS_JET[noise_class_of(profile_idx) as usize]
}

/// Back-out the NPD-tail residual coefficient (dB/m) for the physics-form
/// extrapolation `SEL = SEL_ref − 20·log10(d/d_ref) − α · (d − d_ref)`
/// used beyond 25 000 ft. After removing the spherical-spreading anchor
/// `−20·log10(d/d_ref)` from each tail point, fits the residual linearly
/// in `d` by least squares over (10 000, 16 000, 25 000) ft.
///
/// **What this is, and what it isn't.** It is *not* a generic ISO 9613-1
/// broadband atmospheric-absorption coefficient. It is the slope that
/// reproduces this profile's own NPD curve when the tail is paired with
/// the `−20·log10` divergence term. It happens to land in the same range
/// as ISO 9613-1 broadband α for typical aircraft spectra at standard
/// atmosphere — jets ≈ 0.8–1.1 dB/km, turboprops / LightGA ≈ 0.6–0.9
/// dB/km — but the two are *not* interchangeable. Doc 29 Vol 2
/// Appendix F prescribes exactly this form for extrapolation beyond the
/// last NPD point; any change to the divergence term (e.g. swapping for
/// `−10·log10`) requires re-fitting α on the same form, not borrowing α
/// from another standard.
fn compute_alpha_eff(sel: &[f64; 10]) -> f64 {
    let d_m = [
        NPD_DIST_FT[7] / FT_PER_M, // 10 000 ft → 3 048 m
        NPD_DIST_FT[8] / FT_PER_M, // 16 000 ft → 4 877 m
        NPD_DIST_FT[9] / FT_PER_M, // 25 000 ft → 7 620 m (= AIRCRAFT_NPD_REF_SLANT_M)
    ];
    let residuals = [
        sel[7] + 20.0 * (d_m[0] / AIRCRAFT_NPD_REF_SLANT_M).log10(),
        sel[8] + 20.0 * (d_m[1] / AIRCRAFT_NPD_REF_SLANT_M).log10(),
        sel[9],
    ];
    let n = 3.0_f64;
    let sx: f64 = d_m.iter().sum();
    let sy: f64 = residuals.iter().sum();
    let sxx: f64 = d_m.iter().map(|x| x * x).sum();
    let sxy: f64 = d_m.iter().zip(residuals.iter()).map(|(x, y)| x * y).sum();
    let slope = (n * sxy - sx * sy) / (n * sxx - sx * sx);
    (-slope).max(0.0)
}

impl NpdProfile {
    /// NPD-tail residual coefficient (dB/m), back-fitted from this profile's
    /// last three NPD points — see `compute_alpha_eff` for the warning that
    /// this is *not* a swap-in replacement for ISO 9613-1 atmospheric α.
    /// Cached per (profile, direction) on first use.
    #[inline]
    pub fn alpha_eff(&self, is_departure: bool) -> f64 {
        if is_departure {
            *self
                .alpha_eff_departure
                .get_or_init(|| compute_alpha_eff(&self.departure_sel))
        } else {
            *self
                .alpha_eff_approach
                .get_or_init(|| compute_alpha_eff(&self.approach_sel))
        }
    }

    /// Slant distance (meters) at which raw NPD SEL drops to `threshold_db`.
    /// Log-linear interpolation within the NPD table; physics-based
    /// extrapolation beyond 25 000 ft using per-profile `alpha_eff`
    /// (`SEL = SEL_ref − 20·log10(d/d_ref) − α·(d − d_ref)`). Capped at
    /// `AIRCRAFT_NPD_REACH_CAP_M`.
    pub fn estimate_reach_m(&self, threshold_db: f64, is_departure: bool) -> f64 {
        let sel = if is_departure {
            &self.departure_sel
        } else {
            &self.approach_sel
        };
        let last = sel.len() - 1;

        // Threshold louder than closest NPD point → minimal reach.
        if threshold_db >= sel[0] {
            return NPD_DIST_FT[0] / FT_PER_M;
        }

        // Inside the NPD table: log-linear interpolation.
        if threshold_db > sel[last] {
            for i in 0..last {
                if threshold_db >= sel[i + 1] {
                    let frac = (threshold_db - sel[i]) / (sel[i + 1] - sel[i]);
                    let log_d = LOG_DIST[i] + frac * (LOG_DIST[i + 1] - LOG_DIST[i]);
                    return (10.0_f64.powf(log_d) / FT_PER_M).min(AIRCRAFT_NPD_REACH_CAP_M);
                }
            }
            return AIRCRAFT_NPD_REACH_CAP_M;
        }

        // Beyond the table: bisect the physics kernel in [d_ref, cap]. Kernel
        // is strictly monotone decreasing, so a zero crossing exists when
        // SEL(cap) < threshold; otherwise clamp at the cap.
        let alpha = self.alpha_eff(is_departure);
        let sel_at = |d: f64| {
            sel[last]
                - 20.0 * (d / AIRCRAFT_NPD_REF_SLANT_M).log10()
                - alpha * (d - AIRCRAFT_NPD_REF_SLANT_M)
        };
        if sel_at(AIRCRAFT_NPD_REACH_CAP_M) >= threshold_db {
            return AIRCRAFT_NPD_REACH_CAP_M;
        }
        let mut lo = AIRCRAFT_NPD_REF_SLANT_M;
        let mut hi = AIRCRAFT_NPD_REACH_CAP_M;
        for _ in 0..32 {
            let mid = 0.5 * (lo + hi);
            if sel_at(mid) > threshold_db {
                lo = mid;
            } else {
                hi = mid;
            }
            if (hi - lo) < 0.5 {
                break;
            }
        }
        0.5 * (lo + hi)
    }
}

/// Interpolate SEL at a given slant distance (Doc 29 §4.2, Eq. 4-4/4-5).
/// Log-linear interpolation in distance.
#[inline]
pub fn interpolate_sel(profile: &NpdProfile, slant_ft: f64, is_departure: bool) -> f64 {
    let log_d = slant_ft.max(100.0).log10();
    interpolate_sel_logd(profile, log_d, is_departure)
}

// NPD lookup table — pre-built at first access from `interpolate_sel_logd`.
// Shared by popup `segment_sel_with_overrides` and tile-painter scatter.
// 128 bins keep the linear-log interpolation sag < 0.05 dB against the
// convex physics tail (`−20·log10(d) − α·d` beyond 25 000 ft) where the
// linear-in-meters absorption curves downward faster than log-linear
// between bin anchors.
//
// Lookup cost: ~5 cycles (branchless index + 1 fmadd) vs ~25 for the binary
// search inside `interpolate_sel_logd`. Pipeline batched scatter and popup
// per-segment loop both call `NpdLuts::shared().lookup(...)` so SEL lookups
// match by construction.

pub const NPD_LUT_BINS: usize = 128;
pub const NPD_LUT_LOG_MIN: f64 = 2.0; // log10(100 ft)
pub const NPD_LUT_LOG_MAX: f64 = 5.5; // log10(316 k ft)
pub const NPD_LUT_STEP: f64 = (NPD_LUT_LOG_MAX - NPD_LUT_LOG_MIN) / NPD_LUT_BINS as f64;
pub const NPD_LUT_INV_STEP: f64 = NPD_LUT_BINS as f64 / (NPD_LUT_LOG_MAX - NPD_LUT_LOG_MIN);

pub fn build_npd_lut(profile: &NpdProfile, is_departure: bool) -> [f64; NPD_LUT_BINS + 1] {
    let mut lut = [0.0f64; NPD_LUT_BINS + 1];
    // `i` is both the bin value (`log_d` from `i`) and the write index — kept as a
    // range loop (init-time LUT fill; an enumerate() rewrite would still need `i`).
    #[allow(clippy::needless_range_loop)]
    for i in 0..=NPD_LUT_BINS {
        let log_d = NPD_LUT_LOG_MIN + i as f64 * NPD_LUT_STEP;
        lut[i] = interpolate_sel_logd(profile, log_d, is_departure);
    }
    lut
}

#[inline(always)]
pub fn fast_npd_lookup(lut: &[f64; NPD_LUT_BINS + 1], log_d: f64) -> f64 {
    // `.max(0.0)` guards against wrap-to-huge-usize when log_d dips fractionally
    // below NPD_LUT_LOG_MIN due to float rounding at the 100 ft clamp boundary.
    let t = ((log_d - NPD_LUT_LOG_MIN) * NPD_LUT_INV_STEP).max(0.0);
    let idx = (t as usize).min(NPD_LUT_BINS - 1);
    let frac = t - idx as f64;
    lut[idx] + frac * (lut[idx + 1] - lut[idx])
}

/// Per-noise-class NPD LUTs (NUM_CLASSES classes × 2 directions × 3 metrics).
/// Single global instance — built once on first access, reused across
/// pipeline batches and popup queries. Sized by `NUM_CLASSES`: each class
/// shares its Voronoi anchor's NPD curve, so one LUT per class is exact.
///
/// SEL LUTs feed energy summation; LAmax LUTs feed per-event peak ranking
/// (popup top-flights, band classification). LAmax replaces the hardcoded
/// `sel - 12.0` approximation that had ±5 dB bias across operations.
pub struct NpdLuts {
    approach: Vec<[f64; NPD_LUT_BINS + 1]>,
    departure: Vec<[f64; NPD_LUT_BINS + 1]>,
    approach_lmax: Vec<[f64; NPD_LUT_BINS + 1]>,
    departure_lmax: Vec<[f64; NPD_LUT_BINS + 1]>,
    approach_scaled_distance: Vec<[f64; NPD_LUT_BINS + 1]>,
    departure_scaled_distance: Vec<[f64; NPD_LUT_BINS + 1]>,
}

static NPD_LUTS: OnceLock<NpdLuts> = OnceLock::new();

impl NpdLuts {
    pub fn shared() -> &'static NpdLuts {
        NPD_LUTS.get_or_init(NpdLuts::build)
    }

    fn build() -> Self {
        let mut approach = Vec::with_capacity(NUM_CLASSES);
        let mut departure = Vec::with_capacity(NUM_CLASSES);
        let mut approach_lmax = Vec::with_capacity(NUM_CLASSES);
        let mut departure_lmax = Vec::with_capacity(NUM_CLASSES);
        let mut approach_scaled_distance = Vec::with_capacity(NUM_CLASSES);
        let mut departure_scaled_distance = Vec::with_capacity(NUM_CLASSES);
        for class_idx in 0..NUM_CLASSES {
            let anchor = &PROFILES[CLASS_REP_PROFILE_IDX[class_idx] as usize];
            approach.push(build_npd_lut(anchor, false));
            departure.push(build_npd_lut(anchor, true));
            approach_lmax.push(build_lmax_lut(anchor, false));
            departure_lmax.push(build_lmax_lut(anchor, true));
            approach_scaled_distance.push(build_scaled_distance_lut(anchor, false));
            departure_scaled_distance.push(build_scaled_distance_lut(anchor, true));
        }
        NpdLuts {
            approach,
            departure,
            approach_lmax,
            departure_lmax,
            approach_scaled_distance,
            departure_scaled_distance,
        }
    }

    #[inline(always)]
    pub fn lookup(&self, noise_class: usize, is_dep: bool, log_d: f64) -> f64 {
        let lut = if is_dep {
            &self.departure[noise_class]
        } else {
            &self.approach[noise_class]
        };
        fast_npd_lookup(lut, log_d)
    }

    /// Doc 29 scaled distance `d_λ` (m) of the class anchor at `log_d`
    /// (log10 of the slant in feet); see [`build_scaled_distance_lut`].
    #[inline(always)]
    pub fn lookup_scaled_distance(&self, noise_class: usize, is_dep: bool, log_d: f64) -> f64 {
        let lut = if is_dep {
            &self.departure_scaled_distance[noise_class]
        } else {
            &self.approach_scaled_distance[noise_class]
        };
        fast_npd_lookup(lut, log_d)
    }

    /// SEL and scaled-distance LUTs flattened for GPU upload, `f64` first: the
    /// cruise CUDA path evaluates Doc 29 in double precision. Four blocks of
    /// `NUM_CLASSES` LUTs, each `NPD_LUT_BINS + 1` entries: approach SEL,
    /// departure SEL, approach `d_λ`, departure `d_λ`. The device kernel indexes
    /// it identically to `lookup` / `lookup_scaled_distance`:
    /// `flat[((block * 2 + is_dep) * NUM_CLASSES + class) * (NPD_LUT_BINS + 1) + bin]`.
    pub fn device_luts_flat_f64(&self) -> Vec<f64> {
        let mut v = Vec::with_capacity(4 * NUM_CLASSES * (NPD_LUT_BINS + 1));
        for lut in self
            .approach
            .iter()
            .chain(&self.departure)
            .chain(&self.approach_scaled_distance)
            .chain(&self.departure_scaled_distance)
        {
            v.extend(lut.iter().copied());
        }
        v
    }

    /// The same canonical layout narrowed for the float32 airborne kernel.
    pub fn device_luts_flat_f32(&self) -> Vec<f32> {
        self.device_luts_flat_f64().into_iter().map(|x| x as f32).collect()
    }

    /// Per-event peak A-weighted SPL (LAmax) lookup — replaces the prior
    /// hardcoded `sel - 12.0` constant. Returns the value before any
    /// per-segment ΔI / Λ corrections; callers may apply those if they
    /// need full Doc 29 Eq. 4-12 fidelity (popup peak ranking does not).
    #[inline(always)]
    pub fn lookup_lmax(&self, noise_class: usize, is_dep: bool, log_d: f64) -> f64 {
        let lut = if is_dep {
            &self.departure_lmax[noise_class]
        } else {
            &self.approach_lmax[noise_class]
        };
        fast_npd_lookup(lut, log_d)
    }
}

/// Build a 128-bin LAmax LUT mirroring `build_npd_lut` for SEL. Beyond 25 000 ft
/// we extrapolate via spherical divergence (`−20·log10(d/d_ref)`) plus the SEL
/// per-profile `alpha_eff` for atmospheric absorption — peak SPL and integrated
/// energy share the same source spectrum, so they share `alpha_eff`. The prior
/// clamp at the last NPD point overstated far-cruise LAmax by ~18 dB at 50 k ft
/// slant and caused popup-band false positives.
pub fn build_lmax_lut(profile: &NpdProfile, is_departure: bool) -> [f64; NPD_LUT_BINS + 1] {
    let lmax = if is_departure {
        &profile.departure_lmax
    } else {
        &profile.approach_lmax
    };
    let mut lut = [0.0f64; NPD_LUT_BINS + 1];
    let last = lmax.len() - 1;
    // `i` is both the bin value (`log_d` from `i`) and the write index — kept as a
    // range loop (init-time LUT fill; an enumerate() rewrite would still need `i`).
    #[allow(clippy::needless_range_loop)]
    for i in 0..=NPD_LUT_BINS {
        let log_d = NPD_LUT_LOG_MIN + i as f64 * NPD_LUT_STEP;
        // Below 200 ft: use slope of first two points (matches SEL behaviour).
        if log_d <= LOG_DIST[0] {
            let slope = (lmax[1] - lmax[0]) / (LOG_DIST[1] - LOG_DIST[0]);
            lut[i] = lmax[0] + slope * (log_d - LOG_DIST[0]);
            continue;
        }
        // Beyond the last NPD point (25 000 ft): physics-based extrapolation,
        // mirroring `interpolate_sel_logd`. Atmospheric absorption is linear in
        // metres, so the log-linear NPD slope underestimates loss at large slant.
        if log_d >= LOG_DIST[last] {
            let slant_m = 10.0_f64.powf(log_d) / FT_PER_M;
            let geo = 20.0 * (slant_m / AIRCRAFT_NPD_REF_SLANT_M).log10();
            let atm = profile.alpha_eff(is_departure) * (slant_m - AIRCRAFT_NPD_REF_SLANT_M);
            lut[i] = lmax[last] - geo - atm;
            continue;
        }
        // Inside the table: log-linear interp between adjacent NPD points.
        for j in 0..last {
            if log_d < LOG_DIST[j + 1] {
                let frac = (log_d - LOG_DIST[j]) / (LOG_DIST[j + 1] - LOG_DIST[j]);
                lut[i] = lmax[j] + frac * (lmax[j + 1] - lmax[j]);
                break;
            }
        }
    }
    lut
}

/// NPD interpolation using pre-computed log10(distance_ft).
/// Avoids redundant log10 call when log_d is already available.
#[inline(always)]
pub fn interpolate_sel_logd(profile: &NpdProfile, log_d: f64, is_departure: bool) -> f64 {
    let sel = if is_departure {
        &profile.departure_sel
    } else {
        &profile.approach_sel
    };
    let last = sel.len() - 1;

    if log_d <= LOG_DIST[0] {
        let slope = (sel[1] - sel[0]) / (LOG_DIST[1] - LOG_DIST[0]);
        return sel[0] + slope * (log_d - LOG_DIST[0]);
    }
    // Beyond the last NPD point: physics-based extrapolation. Atmospheric
    // absorption is linear in meters, so the log-linear Doc 29 slope
    // underestimates loss at large slant. Use spherical divergence
    // (−20·log10) + per-profile α_eff·(d − d_ref). See `compute_alpha_eff`.
    if log_d >= LOG_DIST[last] {
        let slant_m = 10.0_f64.powf(log_d) / FT_PER_M;
        let geo = 20.0 * (slant_m / AIRCRAFT_NPD_REF_SLANT_M).log10();
        let atm = profile.alpha_eff(is_departure) * (slant_m - AIRCRAFT_NPD_REF_SLANT_M);
        return sel[last] - geo - atm;
    }

    for i in 0..last {
        if log_d <= LOG_DIST[i + 1] {
            let frac = (log_d - LOG_DIST[i]) / (LOG_DIST[i + 1] - LOG_DIST[i]);
            return sel[i] + frac * (sel[i + 1] - sel[i]);
        }
    }
    sel[last]
}

/// Per-noise-class reach² (m²) at the standard 40 dB SEL threshold, indexed
/// `[noise_class][is_departure as usize]`. Pre-built at first access so the
/// hot-path R-tree pre-filter (popup `lib.rs`, pipeline group bbox) can drop
/// segments via a squared-distance compare without invoking
/// `Profile::estimate_reach_m` per segment.
///
/// Keyed by `CLASS_REP_PROFILE_IDX` because the kernel always emits via the
/// class anchor — pre-filter and kernel must agree on which NPD curve sets
/// the 40 dB envelope, otherwise either false negatives (envelope < kernel
/// reach) or wasted candidates (envelope > kernel reach) leak through.
pub static REACH_SQ_TABLE: LazyLock<[[f64; 2]; NUM_CLASSES]> = LazyLock::new(|| {
    std::array::from_fn(|class_idx| {
        let p = &PROFILES[CLASS_REP_PROFILE_IDX[class_idx] as usize];
        [
            p.estimate_reach_m(AIRCRAFT_NPD_REACH_THRESHOLD_DB, false)
                .powi(2),
            p.estimate_reach_m(AIRCRAFT_NPD_REACH_THRESHOLD_DB, true)
                .powi(2),
        ]
    })
});

#[cfg(test)]
mod tests;
