/** Generate continuity/taper model data from the engine's authoritative Rust tables. */

import { readFileSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { pathToFileURL } from 'node:url'

export function generateRoadPlanningDefaults(): string {
  const read = (path: string) => readFileSync(new URL(`../engine/noise-compute/src/${path}`, import.meta.url), 'utf8')
  const defaults = read('defaults.rs'), normalize = read('normalize/road.rs')
  const tuples = defaults.match(/pub const WORLD_DEFAULT:[\s\S]*?= \[([\s\S]*?)\n\];/)?.[1]
  if (!tuples) throw new Error('missing Rust WORLD_DEFAULT')
  const world = [...tuples.matchAll(/\(([\d.,\s]+)\)/g)].map(match => match[1].split(',').map(Number))
  const speedBody = normalize.match(/fn default_road_speed\([\s\S]*?match class_idx \{([\s\S]*?)\n    \}/)?.[1]
  const speedArms = [...(speedBody ?? '').matchAll(/(\d+|_) => ([\d.]+)/g)]
  const fallback = Number(speedArms.find(match => match[1] === '_')?.[2])
  const legacy = world.map((_, index) => Number(speedArms.find(match => match[1] === String(index))?.[2] ?? fallback))
  const cz = read('country_speed_defaults_generated.rs').match(/\(b"CZ", \[([\d, ]+)\]\)/)?.[1].split(',').map(Number)
  const mask = defaults.match(/const GDP_SCALED_MASK:[^=]+= ([^;]+);/)?.[1]
  const scaled = [...(mask ?? '').matchAll(/1 << (\d+)/g)].map(match => Number(match[1]))
  const sentinel = read('normalize/mod.rs').match(/const DERESTRICTED_SPEED_KMH: f64 = ([\d.]+);/)?.[1]
  if (world.length !== 13 || world.some(row => row.length !== 4 || row.some(value => !Number.isFinite(value))) ||
      legacy.some(value => !Number.isFinite(value)) || cz?.length !== 4 || !scaled.length || !sentinel) {
    throw new Error('unsupported Rust road-default table shape; update the generator explicitly')
  }
  return '/** Generated by pipeline/generate-road-planning-defaults.ts; edit authoritative engine tables. */\n\n' +
    `export const WORLD_DEFAULT = ${JSON.stringify(world)} as const\n` +
    `export const LEGACY_SPEED = ${JSON.stringify(legacy)} as const\n` +
    `export const CZ_SPEEDS = ${JSON.stringify(cz)} as const\n` +
    `export const GDP_SCALED_CLASSES = ${JSON.stringify(scaled)} as const\n` +
    `export const DERESTRICTED_SPEED_KMH = ${Number(sentinel)}\n`
}

if (process.argv[1] && import.meta.url === pathToFileURL(resolve(process.argv[1])).href) {
  const target = new URL('./lib/road-planning-defaults.generated.ts', import.meta.url)
  const output = generateRoadPlanningDefaults()
  if (process.argv.length === 3 && process.argv[2] === '--check') {
    if (readFileSync(target, 'utf8') !== output) throw new Error('stale road-planning defaults: regenerate')
  } else if (process.argv.length === 2) writeFileSync(target, output)
  else throw new Error('usage: generate-road-planning-defaults.ts [--check]')
}
