//! MEASURED country × road_class traffic defaults (M6.3 regional
//! calibration). Generated by `scripts/gen-region-defaults-rs.mjs` from
//! national traffic censuses — every number is the MEDIAN of measured
//! per-section counts, never estimated:
//!
//!
//! Cascade position (`defaults.rs::country_default`): BELOW city arms,
//! ABOVE the hand-tuned country arms. A country present here has its
//! hand-tuned arm deleted (superseded by measured data). Classes a census
//! does not cover stay absent here and fall through to the hand-tuned /
//! GDP-scale arms below — the table claims only what the data measured.
//!
//! Refresh: `node scripts/gen-region-defaults-rs.mjs` (commit this file
//! with the script change; the census CSV cache is a pipeline artifact).

use crate::defaults::Aadt;

/// (iso, engine road_class, (light, medium, heavy, moto)) — veh/day both
/// directions. Sorted by (iso, class) for binary search.
pub const REGION_DEFAULTS: &[(&[u8; 2], u8, Aadt)] = &[];

/// Measured default for (country, road_class), or None when no census
/// covers that arm — the caller then falls through to the hand-tuned
/// country arms and the GDP-scale fallback.
pub fn region_default(iso: &[u8; 2], class: u8) -> Option<Aadt> {
    REGION_DEFAULTS
        .binary_search_by(|(i, c, _)| (**i, *c).cmp(&(*iso, class)))
        .ok()
        .map(|idx| REGION_DEFAULTS[idx].2)
}
