//! Generated by `pipeline/lib/gen-sources-rs.ts` — DO NOT EDIT MANUALLY.
//!
//! Rust mirror of `pipeline/lib/sources.ts`. Regenerate via:
//!
//! ```bash
//! cd pipeline && npm run gen:sources
//! ```
//!
//! This file is committed to git (no `build.rs` / node dependency in the
//! Rust build — plan v5 /gg W: keep noise-compute a pure-Rust crate).

use serde::{Deserialize, Serialize};

/// How authoritative a dataset is. Must stay aligned with the TypeScript
/// `Provenance` union in `pipeline/lib/sources.ts`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum Provenance {
    #[serde(rename = "city-measured")]
    CityMeasured,
    #[serde(rename = "national-measured")]
    NationalMeasured,
    #[serde(rename = "continental-measured")]
    ContinentalMeasured,
    #[serde(rename = "global-measured")]
    GlobalMeasured,
    #[serde(rename = "national-proxy")]
    NationalProxy,
    #[serde(rename = "heuristic")]
    Heuristic,
    #[serde(rename = "baseline")]
    Baseline,
    #[serde(rename = "none")]
    None,
}

impl Provenance {
    /// Ranking for overwrite decisions. Higher wins. Mirrors
    /// `pipeline/lib/sources.ts::PROVENANCE_RANK`.
    pub fn rank(self) -> u8 {
        match self {
            Self::CityMeasured => 7,
            Self::NationalMeasured => 6,
            Self::ContinentalMeasured => 5,
            Self::GlobalMeasured => 4,
            Self::NationalProxy => 3,
            Self::Heuristic => 2,
            Self::Baseline => 1,
            Self::None => 0,
        }
    }

    /// Stable string form for logging and JSON — matches the TypeScript union.
    pub fn as_str(self) -> &'static str {
        match self {
            Self::CityMeasured => "city-measured",
            Self::NationalMeasured => "national-measured",
            Self::ContinentalMeasured => "continental-measured",
            Self::GlobalMeasured => "global-measured",
            Self::NationalProxy => "national-proxy",
            Self::Heuristic => "heuristic",
            Self::Baseline => "baseline",
            Self::None => "none",
        }
    }

    /// True if this source represents real measured data (any measured tier —
    /// city, national, continental or global-scale observational). Used by
    /// `access_factor` to pass measured AADT through without re-applying access
    /// multipliers (a real count already reflects the restriction). Deliberately
    /// EXCLUDES `NationalProxy`: a class-default estimate does NOT reflect the
    /// restriction, so the engine must still down-scale it on private / farm /
    /// forestry roads (gg 2026-06-14, Ondra's call).
    pub fn is_measured(self) -> bool {
        matches!(
            self,
            Self::CityMeasured
                | Self::NationalMeasured
                | Self::ContinentalMeasured
                | Self::GlobalMeasured
        )
    }

    /// True if the row carries any enricher-written data (anything except
    /// the `None` sentinel). Equivalent to the legacy `traffic_source > 0`
    /// check, derivable from `dataset_id` via `provenance_of()`.
    pub fn has_data(self) -> bool {
        !matches!(self, Self::None)
    }

    /// Legacy string form for the JSON API contract
    /// (`frontend/src/types/noise.ts::traffic_source` union). Folds the six
    /// Provenance variants into the three strings the frontend currently
    /// understands. When F.4 lands (ts-rs derivation), the frontend will
    /// switch to the full `as_str()` form and this helper goes away.
    pub fn legacy_traffic_source_str(self) -> &'static str {
        match self {
            // NationalProxy folds in here so the popup still shows its dataset
            // attribution; the coarse 3-bucket label can't say "estimate" yet
            // (F.4 as_str() will). The acoustic distinction lives in is_measured().
            Self::CityMeasured
            | Self::NationalMeasured
            | Self::ContinentalMeasured
            | Self::GlobalMeasured
            | Self::NationalProxy => "matched_external",
            Self::Heuristic => "estimated_service_tree",
            Self::Baseline | Self::None => "default_by_class",
        }
    }
}

/// One enrichment dataset. Mirrors the TypeScript `Source` interface.
#[derive(Debug, Clone, Copy)]
pub struct Source {
    pub id: u16,
    pub key: &'static str,
    pub provenance: Provenance,
    pub layer: &'static str,
    pub name: &'static str,
    pub license: Option<&'static str>,
    pub url: Option<&'static str>,
    pub year: Option<u16>,
}

impl Source {
    /// Sentinel "unspecified" entry used for pre-provenance rows (id = 0).
    pub const UNSPECIFIED: Source = SOURCES[0];
}

/// Fixed source id for the single aircraft observational dataset
/// (`global-adsb-planet`). Avoids scattering the magic literal `1`
/// across every aircraft writer / reader.
pub const AIRCRAFT_ADSB_SOURCE_ID: u16 = 1;

/// Binary search by id — SOURCES is emitted sorted by id (generator
/// preserves TS `DATASETS` order, which is id-ascending). Called per
/// road / rail / industrial row in tile-painter + source-reader hot
/// paths, so O(log N) beats the previous O(N).
pub fn get_source(id: u16) -> Option<&'static Source> {
    SOURCES
        .binary_search_by_key(&id, |s| s.id)
        .ok()
        .map(|idx| &SOURCES[idx])
}

/// Shorthand for the common "what's the provenance of this stamp" lookup.
pub fn provenance_of(id: u16) -> Provenance {
    get_source(id).map_or(Provenance::None, |s| s.provenance)
}

/// Compact dataset attribution attached to popup contributors and
/// segments. Mirrors the TS `lookupProvenance` shape so the wire JSON
/// stays unchanged — previously assembled server-side in Node from a
/// duplicate `SOURCES_BY_ID` map. Moved into Rust because (a) the
/// generator already mirrors `SOURCES` here so there is one source of
/// truth, and (b) the Node enrichment was a no-op since the field
/// rename `dataset_id` → `source_id` (provenance came out `null` on
/// every popup).
#[derive(Debug, Clone, Copy, serde::Serialize)]
pub struct DatasetMeta {
    pub name: &'static str,
    pub year: Option<u16>,
    pub license: Option<&'static str>,
    pub url: Option<&'static str>,
    /// Provenance tier of this dataset, forwarded verbatim so the popup UI can
    /// label measured vs national-proxy without re-deriving from a second
    /// registry (the Node/Rust split moved DatasetMeta into Rust for exactly
    /// this — 0db-codex ProvenanceTier consumer). Wire = the serde-rename
    /// kebab (`"national-measured"`, `"national-proxy"`, …).
    pub tier: Provenance,
}

/// `dataset_meta(id)` returns the wire-shape `DatasetMeta { name, year,
/// license, url, tier }` used for popup display. `None` for id 0 / unknown
/// ids — the popup then renders its per-kind fallback line.
pub fn dataset_meta(id: u16) -> Option<DatasetMeta> {
    if id == 0 {
        return None; // sentinel row exists in SOURCES but is not a dataset
    }
    get_source(id).map(|s| DatasetMeta {
        name: s.name,
        year: s.year,
        license: s.license,
        url: s.url,
        tier: s.provenance,
    })
}

pub const SOURCES: &[Source] = &[
    Source {
        id: 0,
        key: "unspecified",
        provenance: Provenance::None,
        layer: "any",
        name: "Unspecified / pre-provenance legacy",
        license: None,
        url: None,
        year: None,
    },
    Source {
        id: 1,
        key: "global-adsb-planet",
        provenance: Provenance::GlobalMeasured,
        layer: "aircraft",
        name: "ADSBexchange planet TAR archives",
        license: Some("CC-BY-SA-4.0"),
        url: Some("https://www.adsbexchange.com/"),
        year: Some(2024),
    },
    Source {
        id: 10,
        key: "eu-city-traffic",
        provenance: Provenance::ContinentalMeasured,
        layer: "roads",
        name: "EU Harmonized Traffic Volumes (Nature Scientific Data)",
        license: Some("CC-BY-4.0"),
        url: Some("https://github.com/XavB64/traffic-volume-data-EU-cities"),
        year: Some(2023),
    },
    Source {
        id: 11,
        key: "service-tree-heuristic",
        provenance: Provenance::Heuristic,
        layer: "roads",
        name: "Service-tree residential flow heuristic",
        license: Some("project-internal"),
        url: None,
        year: Some(2025),
    },
    Source {
        id: 12,
        key: "road-continuity-heuristic",
        provenance: Provenance::Heuristic,
        layer: "roads",
        name: "Same-ref continuity fill (junction-bounded)",
        license: Some("project-internal"),
        url: None,
        year: Some(2026),
    },
    Source {
        id: 20,
        key: "cz-rsd-scitani",
        provenance: Provenance::NationalMeasured,
        layer: "roads",
        name: "ŘSD Celostátní sčítání dopravy",
        license: Some("CC-BY-4.0"),
        url: Some("https://geoportal.rsd.cz/"),
        year: Some(2020),
    },
    Source {
        id: 21,
        key: "us-fhwa-hpms",
        provenance: Provenance::NationalMeasured,
        layer: "roads",
        name: "FHWA Highway Performance Monitoring System",
        license: Some("public-domain"),
        url: Some("https://www.fhwa.dot.gov/policyinformation/hpms.cfm"),
        year: Some(2022),
    },
    Source {
        id: 22,
        key: "de-bast-autobahn",
        provenance: Provenance::NationalMeasured,
        layer: "roads",
        name: "BASt SVZ Autobahnen",
        license: Some("DL-DE BY 2.0"),
        url: Some("https://www.bast.de/"),
        year: Some(2021),
    },
    Source {
        id: 23,
        key: "de-bast-bundesstrassen",
        provenance: Provenance::NationalMeasured,
        layer: "roads",
        name: "BASt SVZ Bundesstraßen",
        license: Some("DL-DE BY 2.0"),
        url: Some("https://www.bast.de/"),
        year: Some(2021),
    },
    Source {
        id: 24,
        key: "fr-cerema-tmja",
        provenance: Provenance::NationalMeasured,
        layer: "roads",
        name: "Cerema Trafic Moyen Journalier Annuel",
        license: Some("etalab-2.0"),
        url: Some("https://www.data.gouv.fr/"),
        year: Some(2024),
    },
    Source {
        id: 100,
        key: "global-gtfs-transit",
        provenance: Provenance::ContinentalMeasured,
        layer: "railways",
        name: "Continental GTFS transit feeds (aggregated; mostly Europe + AU/IN)",
        license: Some("mixed (per-operator)"),
        url: None,
        year: Some(2025),
    },
    Source {
        id: 110,
        key: "cz-szcd-gtfs",
        provenance: Provenance::NationalMeasured,
        layer: "railways",
        name: "Správa železnic GTFS",
        license: Some("CC-BY-4.0"),
        url: Some("https://www.spravazeleznic.cz/"),
        year: Some(2025),
    },
    Source {
        id: 200,
        key: "cz-ruian-vfr",
        provenance: Provenance::NationalMeasured,
        layer: "buildings",
        name: "ČÚZK RÚIAN VFR",
        license: Some("CC-BY-4.0"),
        url: Some("https://www.cuzk.cz/Uvod/Produkty-a-sluzby/RUIAN/"),
        year: Some(2024),
    },
    Source {
        id: 201,
        key: "es-catastro",
        provenance: Provenance::NationalMeasured,
        layer: "buildings",
        name: "Dirección General del Catastro",
        license: Some("CC-BY-4.0"),
        url: Some("https://www.catastro.minhap.es/"),
        year: Some(2024),
    },
    Source {
        id: 300,
        key: "global-gppd",
        provenance: Provenance::GlobalMeasured,
        layer: "industrial",
        name: "Global Power Plant Database",
        license: Some("CC-BY-4.0"),
        url: Some("https://datasets.wri.org/dataset/globalpowerplantdatabase"),
        year: Some(2021),
    },
    Source {
        id: 301,
        key: "global-uswtdb",
        provenance: Provenance::NationalMeasured,
        layer: "industrial",
        name: "US Wind Turbine Database",
        license: Some("public-domain"),
        url: Some("https://eerscmap.usgs.gov/uswtdb/"),
        year: Some(2024),
    },
    Source {
        id: 310,
        key: "europe-eprtr",
        provenance: Provenance::ContinentalMeasured,
        layer: "industrial",
        name: "European Pollutant Release and Transfer Register",
        license: Some("CC-BY-4.0"),
        url: Some("https://industry.eea.europa.eu/"),
        year: Some(2022),
    },
    Source {
        id: 320,
        key: "cz-irz",
        provenance: Provenance::NationalMeasured,
        layer: "industrial",
        name: "ČHMÚ Integrovaný registr znečišťování",
        license: Some("CC-BY-4.0"),
        url: Some("https://www.irz.cz/"),
        year: Some(2023),
    },
    Source {
        id: 330,
        key: "global-industrial-national-mix",
        provenance: Provenance::GlobalMeasured,
        layer: "industrial",
        name: "OSM-derived per-country industrial (may include GEM/GPPD/USWTDB matches)",
        license: Some("ODbL-1.0"),
        url: Some("https://www.openstreetmap.org/"),
        year: Some(2025),
    },
    Source {
        id: 331,
        key: "global-gem-steel",
        provenance: Provenance::GlobalMeasured,
        layer: "industrial",
        name: "GEM Global Iron and Steel Tracker",
        license: Some("CC-BY-4.0"),
        url: Some("https://globalenergymonitor.org/projects/global-iron-and-steel-tracker/"),
        year: Some(2025),
    },
    Source {
        id: 332,
        key: "global-gem-cement",
        provenance: Provenance::GlobalMeasured,
        layer: "industrial",
        name: "GEM Global Cement and Concrete Tracker",
        license: Some("CC-BY-4.0"),
        url: Some("https://globalenergymonitor.org/projects/global-cement-and-concrete-tracker/"),
        year: Some(2025),
    },
    Source {
        id: 333,
        key: "global-gem-coalmine",
        provenance: Provenance::GlobalMeasured,
        layer: "industrial",
        name: "GEM Global Coal Mine Tracker",
        license: Some("CC-BY-4.0"),
        url: Some("https://globalenergymonitor.org/projects/global-coal-mine-tracker/"),
        year: Some(2025),
    },
    Source {
        id: 1004,
        key: "ar-national-roads",
        provenance: Provenance::NationalMeasured,
        layer: "roads",
        name: "DNV TMDA 2017-18 + IGN GeoServer",
        license: Some("public-data"),
        url: Some("https://ide.transporte.gob.ar/geoserver/observ/ows"),
        year: Some(2018),
    },
    Source {
        id: 1013,
        key: "bo-national-roads",
        provenance: Provenance::NationalProxy,
        layer: "roads",
        name: "ABC Red Vial Fundamental (community ArcGIS mirror)",
        license: Some("community-mirror"),
        url: Some("https://services2.arcgis.com/1GTOs4RWV6SKu0wr/"),
        year: Some(2024),
    },
    Source {
        id: 1014,
        key: "br-national-roads",
        provenance: Provenance::NationalProxy,
        layer: "roads",
        name: "DNIT Rodovias Federais",
        license: Some("public-data"),
        url: Some("https://www.dnit.gov.br/"),
        year: Some(2017),
    },
    Source {
        id: 1019,
        key: "ca-national-roads",
        provenance: Provenance::NationalMeasured,
        layer: "roads",
        name: "Quebec MTQ DJMA",
        license: Some("CC-BY-4.0"),
        url: Some("https://www.donneesquebec.ca/recherche/dataset/debit-de-circulation"),
        year: Some(2024),
    },
    Source {
        id: 1023,
        key: "cl-national-roads",
        provenance: Provenance::NationalMeasured,
        layer: "roads",
        name: "MOP Vialidad Red Vial + Plan Nacional de Censos TMDA",
        license: Some("public-data"),
        url: Some("https://rest-sit.mop.gob.cl/"),
        year: Some(2025),
    },
    Source {
        id: 1025,
        key: "cn-national-roads",
        provenance: Provenance::NationalProxy,
        layer: "roads",
        name: "China Highway Network (ArcGIS mirror) + tier defaults",
        license: Some("community-mirror"),
        url: Some("https://services1.arcgis.com/ERdCHt0sNM6dENSD/"),
        year: Some(2024),
    },
    Source {
        id: 1026,
        key: "co-national-roads",
        provenance: Provenance::NationalMeasured,
        layer: "roads",
        name: "INVIAS Red Vial Nacional + TPDS_NUBE TPDA",
        license: Some("public-data"),
        url: Some("https://services6.arcgis.com/kyerLIHvrND0OSya/"),
        year: Some(2024),
    },
    Source {
        id: 1031,
        key: "dk-national-roads",
        provenance: Provenance::NationalMeasured,
        layer: "roads",
        name: "Vejdirektoratet Mastra",
        license: Some("CC-BY-4.0"),
        url: Some("https://www.opendata.dk/vejdirektoratet/taellinger-nogletal-mastra"),
        year: Some(2025),
    },
    Source {
        id: 1034,
        key: "ec-national-roads",
        provenance: Provenance::NationalProxy,
        layer: "roads",
        name: "CONGOPE Red Vial Ecuador (ArcGIS mirror)",
        license: Some("public-data"),
        url: Some("https://services6.arcgis.com/pYn2F4v1aESZqj1u/"),
        year: Some(2024),
    },
    Source {
        id: 1037,
        key: "es-national-roads",
        provenance: Provenance::NationalMeasured,
        layer: "roads",
        name: "MITMA Mapa de Tráfico",
        license: Some("CC-BY-4.0"),
        url: Some("https://mapatrafico.transportes.gob.es/"),
        year: Some(2022),
    },
    Source {
        id: 1039,
        key: "fi-national-roads",
        provenance: Provenance::NationalMeasured,
        layer: "roads",
        name: "Väylävirasto Liikennemäärät",
        license: Some("CC-BY-4.0"),
        url: Some("https://avoindata.suomi.fi/data/fi/dataset/liikennemaarat"),
        year: Some(2024),
    },
    Source {
        id: 1041,
        key: "gb-national-roads",
        provenance: Provenance::NationalMeasured,
        layer: "roads",
        name: "DfT AADF (Annual Average Daily Flow)",
        license: Some("Open Government Licence v3.0"),
        url: Some("https://roadtraffic.dft.gov.uk/"),
        year: Some(2024),
    },
    Source {
        id: 1048,
        key: "id-national-roads",
        provenance: Provenance::NationalMeasured,
        layer: "roads",
        name: "Bina Marga GIS (PUPR) — Jalan Daerah + Nasional + Tol",
        license: Some("public-data"),
        url: Some("https://gisportal.binamarga.pu.go.id/"),
        year: Some(2024),
    },
    Source {
        id: 1049,
        key: "ie-national-roads",
        provenance: Provenance::NationalMeasured,
        layer: "roads",
        name: "TII Counter Sites + Daily Class Aggregate",
        license: Some("CC-BY-4.0"),
        url: Some("https://data.tii.ie/"),
        year: Some(2020),
    },
    Source {
        id: 1050,
        key: "in-national-roads",
        provenance: Provenance::NationalProxy,
        layer: "roads",
        name: "Bharatmala Road Network (Esri Living Atlas India)",
        license: Some("public-data"),
        url: Some("https://livingatlas.esri.in/"),
        year: Some(2024),
    },
    Source {
        id: 1054,
        key: "it-national-roads",
        provenance: Provenance::NationalMeasured,
        layer: "roads",
        name: "Anas TGM (Traffico Giornaliero Medio)",
        license: Some("CC-BY-4.0"),
        url: Some("https://www.stradeanas.it/"),
        year: Some(2024),
    },
    Source {
        id: 1088,
        key: "no-national-roads",
        provenance: Provenance::NationalMeasured,
        layer: "roads",
        name: "NVDB Trafikkmengde (Statens vegvesen)",
        license: Some("NLOD 2.0"),
        url: Some("https://nvdbapiles.atlas.vegvesen.no/"),
        year: Some(2025),
    },
    Source {
        id: 1090,
        key: "nz-national-roads",
        provenance: Provenance::NationalMeasured,
        layer: "roads",
        name: "NZTA Carriageway + Auckland Transport AADT",
        license: Some("CC-BY-4.0"),
        url: Some("https://opendata-nzta.opendata.arcgis.com/"),
        year: Some(2024),
    },
    Source {
        id: 1093,
        key: "pe-national-roads",
        provenance: Provenance::NationalMeasured,
        layer: "roads",
        name: "MTC Provías Red Vial Nacional + dIMD (ArcGIS mirror)",
        license: Some("public-data"),
        url: Some("https://services6.arcgis.com/G8JFnqCHKQ9vb8YW/"),
        year: Some(2024),
    },
    Source {
        id: 1095,
        key: "ph-national-roads",
        provenance: Provenance::NationalProxy,
        layer: "roads",
        name: "DPWH Road Classification (ArcGIS)",
        license: Some("public-data"),
        url: Some("https://services1.arcgis.com/IwZZTMxZCmAmFYvF/"),
        year: Some(2026),
    },
    Source {
        id: 1097,
        key: "pl-national-roads",
        provenance: Provenance::NationalMeasured,
        layer: "roads",
        name: "GDDKiA Generalny Pomiar Ruchu (GPR)",
        license: Some("CC-BY-4.0"),
        url: Some("https://www.gov.pl/web/gddkia/generalny-pomiar-ruchu-20202021"),
        year: Some(2021),
    },
    Source {
        id: 1098,
        key: "py-national-roads",
        provenance: Provenance::NationalProxy,
        layer: "roads",
        name: "MOPC Rutas Nacionales (KMZ)",
        license: Some("public-data"),
        url: Some("https://www.mopc.gov.py/red-vial/"),
        year: Some(2023),
    },
    Source {
        id: 1102,
        key: "sa-national-roads",
        provenance: Provenance::NationalMeasured,
        layer: "roads",
        name: "MoT count stations + Riyadh PMS + SA Interactive Atlas",
        license: Some("open-data"),
        url: Some("https://mot.gov.sa/en/open-data"),
        year: Some(2024),
    },
    Source {
        id: 1113,
        key: "th-national-roads",
        provenance: Provenance::NationalMeasured,
        layer: "roads",
        name: "DRR Rural Roads AADT (MOT CKAN mirror) + DOH defaults",
        license: Some("public-data"),
        url: Some("https://datagov.mot.go.th/"),
        year: Some(2024),
    },
    Source {
        id: 1124,
        key: "ve-national-roads",
        provenance: Provenance::NationalProxy,
        layer: "roads",
        name: "VE360 Vialidad (SIGOT community mirror)",
        license: Some("community-mirror"),
        url: Some("https://services6.arcgis.com/lpJCO3ug8HhNiEOV/"),
        year: Some(2019),
    },
    Source {
        id: 2000,
        key: "ae-national-railway",
        provenance: Provenance::NationalMeasured,
        layer: "railways",
        name: "Dubai RTA unified GTFS (via Dubai Pulse)",
        license: Some("open-data"),
        url: Some("https://www.dubaipulse.gov.ae/"),
        year: Some(2025),
    },
    Source {
        id: 2004,
        key: "ar-national-railway",
        provenance: Provenance::NationalProxy,
        layer: "railways",
        name: "IGN GeoServer (Trenes Argentinos + Subte BA)",
        license: Some("public-data"),
        url: Some("https://wms.ign.gob.ar/geoserver/transporte/ows"),
        year: Some(2024),
    },
    Source {
        id: 2005,
        key: "au-national-railway",
        provenance: Provenance::NationalMeasured,
        layer: "railways",
        name: "Australian state rail GTFS (TfNSW + Transperth + Adelaide Metro)",
        license: Some("CC-BY-4.0"),
        url: Some("https://opendata.transport.nsw.gov.au/"),
        year: Some(2025),
    },
    Source {
        id: 2009,
        key: "be-national-railway",
        provenance: Provenance::NationalMeasured,
        layer: "railways",
        name: "Belgian urban rail GTFS (STIB/MIVB + De Lijn + TEC)",
        license: Some("open-data"),
        url: Some("https://stibmivb.opendatasoft.com/"),
        year: Some(2025),
    },
    Source {
        id: 2015,
        key: "ca-national-railway",
        provenance: Provenance::NationalMeasured,
        layer: "railways",
        name: "Canadian rail GTFS (VIA Rail + Metrolinx + TTC + STM + TransLink + OC Transpo + Calgary + ETS)",
        license: Some("open-data"),
        url: Some("https://www.viarail.ca/"),
        year: Some(2025),
    },
    Source {
        id: 2021,
        key: "cn-national-railway",
        provenance: Provenance::NationalProxy,
        layer: "railways",
        name: "Mainland CR + Metros (ArcGIS FeatureServer mirror)",
        license: Some("community-mirror"),
        url: Some("https://services7.arcgis.com/m6uLpqj7MgjPU371/"),
        year: Some(2024),
    },
    Source {
        id: 2024,
        key: "dk-national-railway",
        provenance: Provenance::NationalMeasured,
        layer: "railways",
        name: "Rejseplanen unified GTFS",
        license: Some("open-data"),
        url: Some("https://www.rejseplanen.info/labs/GTFS.zip"),
        year: Some(2025),
    },
    Source {
        id: 2028,
        key: "es-national-railway",
        provenance: Provenance::NationalMeasured,
        layer: "railways",
        name: "Renfe + FGC GTFS",
        license: Some("CC-BY-4.0"),
        url: Some("https://data.renfe.com/"),
        year: Some(2025),
    },
    Source {
        id: 2030,
        key: "fi-national-railway",
        provenance: Provenance::NationalMeasured,
        layer: "railways",
        name: "Finnish rail GTFS (Fintraffic VR + HSL + Tampere Raitiotie)",
        license: Some("CC-BY-4.0"),
        url: Some("https://rata.digitraffic.fi/"),
        year: Some(2025),
    },
    Source {
        id: 2035,
        key: "ie-national-railway",
        provenance: Provenance::NationalMeasured,
        layer: "railways",
        name: "NTA Transport for Ireland unified GTFS",
        license: Some("open-data"),
        url: Some("https://www.transportforireland.ie/"),
        year: Some(2025),
    },
    Source {
        id: 2036,
        key: "il-national-railway",
        provenance: Provenance::NationalMeasured,
        layer: "railways",
        name: "Israeli MoT unified GTFS",
        license: Some("CC-BY-4.0"),
        url: Some("https://www.gov.il/he/pages/gtfs_general_transit_feed_specifications"),
        year: Some(2025),
    },
    Source {
        id: 2037,
        key: "in-national-railway",
        provenance: Provenance::NationalProxy,
        layer: "railways",
        name: "Living Atlas IN Railway Network",
        license: Some("public-data"),
        url: Some("https://livingatlas.esri.in/"),
        year: Some(2024),
    },
    Source {
        id: 2040,
        key: "it-national-railway",
        provenance: Provenance::NationalMeasured,
        layer: "railways",
        name: "Italian regional rail GTFS (Trenitalia + Trenord + GTT + Ferrotramviaria)",
        license: Some("CC-BY-4.0"),
        url: Some("https://dati.toscana.it/"),
        year: Some(2025),
    },
    Source {
        id: 2044,
        key: "kr-national-railway",
        provenance: Provenance::NationalProxy,
        layer: "railways",
        name: "KORAIL operator-class CNOSSOS defaults",
        license: Some("derived-from-OSM"),
        url: None,
        year: Some(2025),
    },
    Source {
        id: 2057,
        key: "mx-national-railway",
        provenance: Provenance::NationalMeasured,
        layer: "railways",
        name: "CDMX SEMOVI unified GTFS",
        license: Some("open-data"),
        url: Some("https://datos.cdmx.gob.mx/dataset/gtfs"),
        year: Some(2025),
    },
    Source {
        id: 2066,
        key: "pl-national-railway",
        provenance: Provenance::NationalMeasured,
        layer: "railways",
        name: "Polish Trains unified GTFS (Kuranowski/PKP PLK)",
        license: Some("CC-BY-4.0"),
        url: Some("https://mkuran.pl/gtfs/"),
        year: Some(2025),
    },
    Source {
        id: 2067,
        key: "pt-national-railway",
        provenance: Provenance::NationalMeasured,
        layer: "railways",
        name: "Portuguese rail GTFS (CP + Metro do Porto + MTS)",
        license: Some("open-data"),
        url: Some("https://publico.cp.pt/gtfs"),
        year: Some(2025),
    },
    Source {
        id: 2073,
        key: "se-national-railway",
        provenance: Provenance::NationalMeasured,
        layer: "railways",
        name: "GTFS Sverige 2 unified (Trafiklab/Samtrafiken)",
        license: Some("open-data"),
        url: Some("https://www.trafiklab.se/"),
        year: Some(2025),
    },
    Source {
        id: 2075,
        key: "th-national-railway",
        provenance: Provenance::NationalMeasured,
        layer: "railways",
        name: "Namtang GTFS (Thailand)",
        license: Some("open-data"),
        url: None,
        year: Some(2025),
    },
    Source {
        id: 9000,
        key: "industrial-name-heuristic",
        provenance: Provenance::Heuristic,
        layer: "industrial",
        name: "OSM industrial name-keyword NACE heuristic",
        license: Some("project-internal"),
        url: None,
        year: Some(2025),
    },
    Source {
        id: 9001,
        key: "global-overture",
        provenance: Provenance::Baseline,
        layer: "buildings",
        name: "Overture Maps buildings (MS/Google/Meta)",
        license: Some("CDLA-Permissive-2.0"),
        url: Some("https://overturemaps.org/"),
        year: Some(2024),
    },
    Source {
        id: 9002,
        key: "global-copernicus-glo30",
        provenance: Provenance::Baseline,
        layer: "any",
        name: "Copernicus GLO-30 DEM",
        license: Some("CC-BY-4.0"),
        url: Some("https://spacedata.copernicus.eu/collections/copernicus-digital-elevation-model"),
        year: Some(2021),
    },
    Source {
        id: 9003,
        key: "city-praha-tsk",
        provenance: Provenance::CityMeasured,
        layer: "roads",
        name: "TSK Praha — Intenzity dopravy",
        license: Some("Prague open data (no explicit CC; city portal terms)"),
        url: Some("https://tsk-praha.cz/"),
        year: Some(2025),
    },
    Source {
        id: 9004,
        key: "city-wien-dauerzaehlstellen",
        provenance: Provenance::CityMeasured,
        layer: "roads",
        name: "Stadt Wien MA46 — Dauerzählstellen DTV",
        license: Some("CC-BY-4.0"),
        url: Some("https://www.data.gv.at/katalog/dataset/stadt-wien_verkehrszhlstellenzhlwertewien"),
        year: Some(2025),
    },
    Source {
        id: 9005,
        key: "city-brno-detectors",
        provenance: Provenance::CityMeasured,
        layer: "roads",
        name: "Brno BKOM — pentlogram intenzity dopravy",
        license: Some("CC-BY-SA-4.0"),
        url: Some("https://data.brno.cz/datasets/intenzita-dopravy-intenzita-vozidel-vehicle-traffic-intensity"),
        year: Some(2023),
    },
    Source {
        id: 9012,
        key: "dz-national-roads",
        provenance: Provenance::NationalProxy,
        layer: "roads",
        name: "Algeria-tuned CNOSSOS class defaults (no open per-segment AADT)",
        license: Some("derived-from-OSM"),
        url: None,
        year: Some(2024),
    },
    Source {
        id: 9013,
        key: "dz-national-railway",
        provenance: Provenance::NationalProxy,
        layer: "railways",
        name: "Algeria operator-class CNOSSOS defaults (SNTF context)",
        license: Some("derived-from-OSM"),
        url: None,
        year: Some(2024),
    },
    Source {
        id: 9180,
        key: "cd-national-roads",
        provenance: Provenance::NationalProxy,
        layer: "roads",
        name: "DR Congo-tuned CNOSSOS class defaults (no open per-segment AADT)",
        license: Some("derived-from-OSM"),
        url: None,
        year: Some(2024),
    },
    Source {
        id: 9181,
        key: "cd-national-railway",
        provenance: Provenance::NationalProxy,
        layer: "railways",
        name: "DR Congo operator-class CNOSSOS defaults (SNCC context)",
        license: Some("derived-from-OSM"),
        url: None,
        year: Some(2024),
    },
    Source {
        id: 9231,
        key: "et-national-roads",
        provenance: Provenance::NationalProxy,
        layer: "roads",
        name: "Ethiopia-tuned CNOSSOS class defaults (ERA context; no open per-segment AADT)",
        license: Some("derived-from-OSM"),
        url: None,
        year: Some(2024),
    },
    Source {
        id: 9232,
        key: "et-national-railway",
        provenance: Provenance::NationalProxy,
        layer: "railways",
        name: "Ethiopia operator-class CNOSSOS defaults (Addis-Djibouti SGR + LRT context)",
        license: Some("derived-from-OSM"),
        url: None,
        year: Some(2024),
    },
    Source {
        id: 9364,
        key: "ir-national-roads",
        provenance: Provenance::NationalProxy,
        layer: "roads",
        name: "Iran-tuned CNOSSOS class defaults (no open per-segment AADT)",
        license: Some("derived-from-OSM"),
        url: None,
        year: Some(2024),
    },
    Source {
        id: 9365,
        key: "ir-national-railway",
        provenance: Provenance::NationalProxy,
        layer: "railways",
        name: "Iran operator-class CNOSSOS defaults (RAI context)",
        license: Some("derived-from-OSM"),
        url: None,
        year: Some(2024),
    },
    Source {
        id: 9368,
        key: "iq-national-roads",
        provenance: Provenance::NationalProxy,
        layer: "roads",
        name: "Iraq-tuned CNOSSOS class defaults (no open per-segment AADT)",
        license: Some("derived-from-OSM"),
        url: None,
        year: Some(2024),
    },
    Source {
        id: 9369,
        key: "iq-national-railway",
        provenance: Provenance::NationalProxy,
        layer: "railways",
        name: "Iraq operator-class CNOSSOS defaults (IRR context)",
        license: Some("derived-from-OSM"),
        url: None,
        year: Some(2024),
    },
    Source {
        id: 9392,
        key: "jp-national-roads",
        provenance: Provenance::NationalMeasured,
        layer: "roads",
        name: "Japan MLIT Road Traffic Census R3 (2021) name/ref join",
        license: Some("derived-from-OSM"),
        url: Some("https://www.mlit.go.jp/road/census/r3/"),
        year: Some(2021),
    },
    Source {
        id: 9398,
        key: "kz-national-roads",
        provenance: Provenance::NationalProxy,
        layer: "roads",
        name: "Kazakhstan-tuned CNOSSOS class defaults (no open per-segment AADT)",
        license: Some("derived-from-OSM"),
        url: None,
        year: Some(2024),
    },
    Source {
        id: 9399,
        key: "kz-national-railway",
        provenance: Provenance::NationalProxy,
        layer: "railways",
        name: "Kazakhstan operator-class CNOSSOS defaults (KTZ context)",
        license: Some("derived-from-OSM"),
        url: None,
        year: Some(2024),
    },
    Source {
        id: 9404,
        key: "ke-national-roads",
        provenance: Provenance::NationalProxy,
        layer: "roads",
        name: "Kenya-tuned CNOSSOS class defaults (no open per-segment AADT)",
        license: Some("derived-from-OSM"),
        url: None,
        year: Some(2024),
    },
    Source {
        id: 9405,
        key: "ke-national-railway",
        provenance: Provenance::NationalProxy,
        layer: "railways",
        name: "Kenya operator-class CNOSSOS defaults (SGR/metre-gauge context)",
        license: Some("derived-from-OSM"),
        url: None,
        year: Some(2024),
    },
    Source {
        id: 9410,
        key: "kr-industrial-names",
        provenance: Provenance::Heuristic,
        layer: "industrial",
        name: "OSM Korean-script industrial name-keyword NACE heuristic",
        license: Some("project-internal"),
        url: None,
        year: Some(2025),
    },
    Source {
        id: 9484,
        key: "mx-national-roads",
        provenance: Provenance::NationalMeasured,
        layer: "roads",
        name: "Mexico SICT/IMT Datos Viales 2025 (200m polyline match)",
        license: Some("derived-from-OSM"),
        url: None,
        year: Some(2025),
    },
    Source {
        id: 9504,
        key: "ma-national-roads",
        provenance: Provenance::NationalProxy,
        layer: "roads",
        name: "Morocco-tuned CNOSSOS class defaults (no open per-segment AADT)",
        license: Some("derived-from-OSM"),
        url: None,
        year: Some(2024),
    },
    Source {
        id: 9505,
        key: "ma-national-railway",
        provenance: Provenance::NationalProxy,
        layer: "railways",
        name: "Morocco operator-class CNOSSOS defaults (ONCF Al Boraq HSR + conventional context)",
        license: Some("derived-from-OSM"),
        url: None,
        year: Some(2024),
    },
    Source {
        id: 9566,
        key: "ng-national-roads",
        provenance: Provenance::NationalProxy,
        layer: "roads",
        name: "Nigeria-tuned CNOSSOS class defaults (FRSC/FERMA portals unavailable)",
        license: Some("derived-from-OSM"),
        url: None,
        year: Some(2024),
    },
    Source {
        id: 9567,
        key: "ng-national-railway",
        provenance: Provenance::NationalProxy,
        layer: "railways",
        name: "Nigeria operator-class CNOSSOS defaults (SGR commissioning context)",
        license: Some("derived-from-OSM"),
        url: None,
        year: Some(2024),
    },
    Source {
        id: 9643,
        key: "ru-national-roads",
        provenance: Provenance::NationalProxy,
        layer: "roads",
        name: "Russia-tuned CNOSSOS class defaults (no open per-segment AADT)",
        license: Some("derived-from-OSM"),
        url: None,
        year: Some(2024),
    },
    Source {
        id: 9644,
        key: "ru-national-railway",
        provenance: Provenance::NationalProxy,
        layer: "railways",
        name: "Russia operator-class CNOSSOS defaults (no open per-segment timetable)",
        license: Some("derived-from-OSM"),
        url: None,
        year: Some(2024),
    },
    Source {
        id: 9729,
        key: "sd-national-roads",
        provenance: Provenance::NationalProxy,
        layer: "roads",
        name: "Sudan-tuned CNOSSOS class defaults (no open per-segment AADT)",
        license: Some("derived-from-OSM"),
        url: None,
        year: Some(2024),
    },
    Source {
        id: 9730,
        key: "sd-national-railway",
        provenance: Provenance::NationalProxy,
        layer: "railways",
        name: "Sudan operator-class CNOSSOS defaults (SRC context)",
        license: Some("derived-from-OSM"),
        url: None,
        year: Some(2024),
    },
    Source {
        id: 9792,
        key: "tr-national-roads",
        provenance: Provenance::NationalProxy,
        layer: "roads",
        name: "Turkey-tuned CNOSSOS class defaults (KGM otoyol/devlet yolu context)",
        license: Some("derived-from-OSM"),
        url: None,
        year: Some(2024),
    },
    Source {
        id: 9793,
        key: "tr-national-railway",
        provenance: Provenance::NationalProxy,
        layer: "railways",
        name: "Turkey operator-class CNOSSOS defaults (TCDD context)",
        license: Some("derived-from-OSM"),
        url: None,
        year: Some(2024),
    },
    Source {
        id: 9804,
        key: "ua-national-roads",
        provenance: Provenance::NationalProxy,
        layer: "roads",
        name: "Ukraine-tuned CNOSSOS class defaults (Ukravtodor context)",
        license: Some("derived-from-OSM"),
        url: None,
        year: Some(2024),
    },
    Source {
        id: 9805,
        key: "ua-national-railway",
        provenance: Provenance::NationalProxy,
        layer: "railways",
        name: "Ukraine operator-class CNOSSOS defaults (Ukrzaliznytsia context)",
        license: Some("derived-from-OSM"),
        url: None,
        year: Some(2024),
    },
    Source {
        id: 9818,
        key: "eg-national-roads",
        provenance: Provenance::NationalProxy,
        layer: "roads",
        name: "Egypt-tuned CNOSSOS class defaults (no open per-segment AADT)",
        license: Some("derived-from-OSM"),
        url: None,
        year: Some(2024),
    },
    Source {
        id: 9819,
        key: "eg-national-railway",
        provenance: Provenance::NationalProxy,
        layer: "railways",
        name: "Egypt operator-class CNOSSOS defaults (no open per-segment timetable)",
        license: Some("derived-from-OSM"),
        url: None,
        year: Some(2024),
    },
    Source {
        id: 9834,
        key: "tz-national-roads",
        provenance: Provenance::NationalProxy,
        layer: "roads",
        name: "Tanzania-tuned CNOSSOS class defaults (TANROADS context)",
        license: Some("derived-from-OSM"),
        url: None,
        year: Some(2024),
    },
    Source {
        id: 9835,
        key: "tz-national-railway",
        provenance: Provenance::NationalProxy,
        layer: "railways",
        name: "Tanzania operator-class CNOSSOS defaults (TRC SGR + TAZARA context)",
        license: Some("derived-from-OSM"),
        url: None,
        year: Some(2024),
    },
    Source {
        id: 9860,
        key: "uz-national-roads",
        provenance: Provenance::NationalProxy,
        layer: "roads",
        name: "Uzbekistan-tuned CNOSSOS class defaults (no open per-segment AADT)",
        license: Some("derived-from-OSM"),
        url: None,
        year: Some(2024),
    },
    Source {
        id: 9861,
        key: "uz-national-railway",
        provenance: Provenance::NationalProxy,
        layer: "railways",
        name: "Uzbekistan operator-class CNOSSOS defaults (UTY Afrosiyob HSR + conventional context)",
        license: Some("derived-from-OSM"),
        url: None,
        year: Some(2024),
    },
    Source {
        id: 9862,
        key: "osm-transition-taper",
        provenance: Provenance::Baseline,
        layer: "roads",
        name: "Transition taper (graded junction-free speed/AADT steps)",
        license: Some("project-internal"),
        url: None,
        year: Some(2026),
    },
    Source {
        id: 9863,
        key: "cz-timetable-silent",
        provenance: Provenance::Baseline,
        layer: "railways",
        name: "CZ timetable-silent residual (CZPTT has no scheduled service)",
        license: Some("project-internal"),
        url: None,
        year: Some(2026),
    },
    Source {
        id: 9864,
        key: "de-national-railway",
        provenance: Provenance::NationalMeasured,
        layer: "railways",
        name: "DELFI national GTFS via gtfs.de (de_full)",
        license: Some("CC-BY-4.0"),
        url: Some("https://gtfs.de/en/feeds/de_full/"),
        year: Some(2026),
    },
    Source {
        id: 9865,
        key: "jp-class-median-fallback",
        provenance: Provenance::NationalProxy,
        layer: "roads",
        name: "Japan MLIT R3 class-median fallback (census-derived, no geometry join)",
        license: Some("derived-from-OSM"),
        url: Some("https://www.mlit.go.jp/road/census/r3/"),
        year: Some(2021),
    },
    Source {
        id: 9866,
        key: "global-ghsl-built-h",
        provenance: Provenance::Baseline,
        layer: "buildings",
        name: "GHS-BUILT-H R2023A ANBH building heights (JRC)",
        license: Some("CC-BY-4.0"),
        url: Some("https://human-settlement.emergency.copernicus.eu/ghs_buH2023.php"),
        year: Some(2018),
    },
    Source {
        id: 9867,
        key: "cz-ipr-praha-vysky",
        provenance: Provenance::CityMeasured,
        layer: "buildings",
        name: "IPR Praha – Relativní výšky budov (building DSM−DTM, 1 m)",
        license: Some("CC-BY-4.0"),
        url: Some("https://opendata.geoportalpraha.cz/maps/ad9aca20e9c042d2b52eb31ff18961b6"),
        year: Some(2023),
    },
];

#[cfg(test)]
mod sources_tests {
    use crate::sources::{get_source, provenance_of, Provenance, Source, SOURCES};

    #[test]
    fn unspecified_is_id_zero_sentinel() {
        let s = &SOURCES[0];
        assert_eq!(s.id, 0);
        assert_eq!(s.key, "unspecified");
        assert_eq!(s.provenance, Provenance::None);
        assert_eq!(Source::UNSPECIFIED.id, 0);
    }

    #[test]
    fn dataset_meta_zero_is_none() {
        assert!(crate::sources::dataset_meta(0).is_none());
        assert!(crate::sources::dataset_meta(20).is_some()); // cz-rsd
    }

    #[test]
    fn dataset_meta_tier_serializes() {
        // The popup UI (0db-codex ProvenanceTier) reads DatasetMeta.tier to
        // label measured vs national-proxy. Pin the wire strings so a rename
        // can't silently break the consumer: id 20 = national-measured,
        // 1013/2037 = national-proxy.
        let m20 = crate::sources::dataset_meta(20).unwrap(); // cz-rsd-scitani
        assert_eq!(m20.tier, Provenance::NationalMeasured);
        assert_eq!(
            serde_json::to_value(m20).unwrap()["tier"],
            "national-measured"
        );
        for proxy in [1013u16, 2037] {
            // bo-national-roads, in-national-railway
            let m = crate::sources::dataset_meta(proxy).unwrap();
            assert_eq!(m.tier, Provenance::NationalProxy);
            assert_eq!(serde_json::to_value(m).unwrap()["tier"], "national-proxy");
        }
    }

    #[test]
    fn no_duplicate_ids() {
        let mut seen = std::collections::HashSet::new();
        for s in SOURCES {
            assert!(seen.insert(s.id), "duplicate id={} (key={})", s.id, s.key);
        }
    }

    #[test]
    fn no_duplicate_keys() {
        let mut seen = std::collections::HashSet::new();
        for s in SOURCES {
            assert!(seen.insert(s.key), "duplicate key={} (id={})", s.key, s.id);
        }
    }

    #[test]
    fn provenance_rank_monotonic() {
        assert!(Provenance::CityMeasured.rank() > Provenance::NationalMeasured.rank());
        assert!(Provenance::NationalMeasured.rank() > Provenance::ContinentalMeasured.rank());
        assert!(Provenance::ContinentalMeasured.rank() > Provenance::GlobalMeasured.rank());
        assert!(Provenance::GlobalMeasured.rank() > Provenance::NationalProxy.rank());
        assert!(Provenance::NationalProxy.rank() > Provenance::Heuristic.rank());
        assert!(Provenance::Heuristic.rank() > Provenance::Baseline.rank());
        assert!(Provenance::Baseline.rank() > Provenance::None.rank());
    }

    #[test]
    fn get_source_looks_up_by_id() {
        let rsd = get_source(20).expect("cz-rsd (id=20) must exist");
        assert_eq!(rsd.key, "cz-rsd-scitani");
        assert_eq!(rsd.provenance, Provenance::NationalMeasured);
    }

    #[test]
    fn provenance_of_unknown_id_is_none() {
        assert_eq!(provenance_of(0), Provenance::None);
        assert_eq!(provenance_of(u16::MAX), Provenance::None);
    }

    #[test]
    fn sources_sorted_by_id_for_binary_search() {
        // get_source uses binary_search_by_key; the generator emits SOURCES
        // in id-ascending order. Lock the invariant so a hand-edit to
        // sources.rs (or a reordered DATASETS) can't silently break lookup.
        for pair in SOURCES.windows(2) {
            assert!(
                pair[0].id < pair[1].id,
                "SOURCES not sorted by id: {} then {}",
                pair[0].id,
                pair[1].id
            );
        }
    }
}
