//! Parser for the reviewed `NOISE_GPU_DEFINES` measurement interface.

use std::collections::BTreeSet;

/// CUDA switches that are intentionally available to measurement builds.
///
/// Everything else is rejected before `nvcc`, especially constants and ABI
/// values generated by `build.rs`. Adding a switch here is therefore a
/// reviewable expansion of the build interface rather than an accidental
/// compiler-option passthrough.
const REVIEWED_EXPERIMENTAL_DEFINES: &[&str] = &[
    "ARC_AZ_F32",
    "ARC_FOOTPRINT_CSR",
    "ARC_HULL_CACHE",
    "ARC_MAX_IV",
    "ARC_MAX_MERGED",
    "ARC_MIN_SPAN",
    "ARC_MIN_SPAN_REALISED",
    "ARC_TRI_WALK",
    "ARC_UNION_BEFORE_SPAN_CLIP",
    "CAND_END_WINDOW_M",
    "CP_SCREEN_DELETE",
    "MULTIFIDELITY_CHEAP_GROUND_DB",
    "MULTIFIDELITY_COMPACT_BYTE_STOP",
    "MULTIFIDELITY_LINE",
    "MULTIFIDELITY_Z13_ADAPTIVE",
    "MULTIFIDELITY_Z13_STRIDE",
    "PENUMBRA",
    "PROF_ABLATE",
    "PROF_BLOCK_MOD",
    "PROF_COUNTERS",
    "SEG_ISECT_F32",
    "SHADOW_MID_STRIDE",
];

pub(crate) fn parse_experimental_defines(raw: &str) -> Result<Vec<String>, String> {
    let mut names = BTreeSet::new();
    let mut parsed = Vec::new();

    for token in raw.split_ascii_whitespace() {
        let body = token.strip_prefix("-D").ok_or_else(|| {
            format!("`{token}` is not one canonical -DNAME or -DNAME=VALUE token")
        })?;
        let (name, value) = match body.split_once('=') {
            Some((_, "")) => return Err(format!("`{token}` has an empty define value")),
            Some((name, value)) => (name, Some(value)),
            None => (body, None),
        };
        if !is_canonical_define_name(name) {
            return Err(format!("`{token}` has a non-canonical macro name"));
        }
        if is_build_generated_define(name) {
            return Err(format!(
                "`{name}` is generated by build.rs and cannot be overridden"
            ));
        }
        if REVIEWED_EXPERIMENTAL_DEFINES.binary_search(&name).is_err() {
            return Err(format!(
                "`{name}` is not in the reviewed experimental define allowlist"
            ));
        }
        validate_experimental_define_value(name, value)?;
        if !names.insert(name) {
            return Err(format!("duplicate macro `{name}` in NOISE_GPU_DEFINES"));
        }

        parsed.push(match value {
            Some(value) => format!("-D{name}={value}"),
            None => format!("-D{name}"),
        });
    }

    Ok(parsed)
}

fn validate_experimental_define_value(name: &str, value: Option<&str>) -> Result<(), String> {
    match name {
        "ARC_UNION_BEFORE_SPAN_CLIP" => match value {
            Some("1") => Ok(()),
            Some(value) => Err(format!(
                "`-D{name}={value}` must use the reviewed per-call pre-clip union value `=1`"
            )),
            None => Err(format!("`-D{name}` must be explicitly set to `=1`")),
        },
        "MULTIFIDELITY_Z13_STRIDE" => match value {
            Some("4" | "8" | "16" | "32") => Ok(()),
            Some(value) => Err(format!(
                "`-D{name}={value}` must use one reviewed pixel stride: 4, 8, 16, or 32"
            )),
            None => Err(format!("`-D{name}` must include an explicit pixel stride")),
        },
        // Adaptive replay and the CPU reference profile are deliberately not
        // part of this ladder. Keeping the accepted value explicit makes a
        // copied runner fail closed instead of silently changing semantics.
        "MULTIFIDELITY_Z13_ADAPTIVE" => match value {
            Some("0") => Ok(()),
            Some(value) => Err(format!(
                "`-D{name}={value}` is disabled for the strict W1 z13 ladder; use `=0`"
            )),
            None => Err(format!("`-D{name}` must be explicitly set to `=0`")),
        },
        _ => Ok(()),
    }
}

fn is_canonical_define_name(name: &str) -> bool {
    let mut bytes = name.bytes();
    matches!(bytes.next(), Some(b'A'..=b'Z'))
        && bytes.all(|byte| byte.is_ascii_uppercase() || byte.is_ascii_digit() || byte == b'_')
}

fn is_build_generated_define(name: &str) -> bool {
    name.starts_with("V2_")
        || name.starts_with("OUT_")
        || name.starts_with("PROF_H0_")
        || name.starts_with("H0_PAIR_DIAGNOSTIC_")
        || matches!(
            name,
            "NPD_NC"
                | "TPX"
                | "BIN_W"
                | "BARRIER_ABI_VERSION"
                | "BARRIER_STRIDE"
                | "SOURCE_SEGMENT_ABI_VERSION"
                | "SOURCE_SEGMENT_STRIDE"
                | "LINE_KERNEL_ARGUMENT_COUNT"
                | "SURFACE_META_ABI_VERSION"
                | "SURFACE_META_SLOTS"
                | "M_LAT"
                | "MULTIFIDELITY_COMPACT_ABI_VERSION"
                | "MULTIFIDELITY_COMPACT_CONTROL_BLOCK_WORDS"
                | "MULTIFIDELITY_COMPACT_CONTROL_WORDS"
                | "MULTIFIDELITY_COMPACT_OUTPUT_ENERGY_BASE"
                | "MULTIFIDELITY_COMPACT_OUTPUT_FAULT_SLOT"
                | "MULTIFIDELITY_COMPACT_OUTPUT_INDEX_SLOT"
                | "MULTIFIDELITY_COMPACT_OUTPUT_STRIDE"
                | "MULTIFIDELITY_COMPACT_RECEIVER_RECORD_WORDS"
                | "OBST_META_STRIDE"
                | "FOOT_BOX_STRIDE"
                | "ARC_DEGENERATE_SPAN"
                | "SEG_ARC_MIN_SPAN_RAD"
                | "SEG_SAMPLES"
                | "ARC_CP_EPS"
                | "ARC_QUADRATURE_MIN_RAD"
                | "GROUND_HARD_FLOOR_DB"
                | "GROUND_SOUND_SPEED"
                | "CNOSSOS_GROUND_ALPHA0"
                | "CNOSSOS_GROUND_DELTA_ZT_COEFF"
                | "P_FAV"
                | "ARC_PENUMBRA_FLOOR_M"
                | "ARC_FUSE_HEIGHT_TOL_M"
                | "ARC_FUSE_RANGE_RATIO_LN"
        )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn reviewed_experimental_defines_keep_canonical_order_and_values() {
        let parsed = parse_experimental_defines(
            "-DARC_TRI_WALK=0 -DMULTIFIDELITY_COMPACT_BYTE_STOP=0 -DPROF_COUNTERS=1 -DPENUMBRA",
        )
        .unwrap();
        assert_eq!(
            parsed,
            [
                "-DARC_TRI_WALK=0",
                "-DMULTIFIDELITY_COMPACT_BYTE_STOP=0",
                "-DPROF_COUNTERS=1",
                "-DPENUMBRA"
            ]
        );
    }

    #[test]
    fn generated_constants_and_abi_defines_are_reserved() {
        for name in [
            "V2_THETA_MAX_RAD",
            "V2_H0_NODE_CAP",
            "V2_H0",
            "OUT_SLOTS_H0",
            "OUT_H0_COUNTERS",
            "BARRIER_ABI_VERSION",
            "SOURCE_SEGMENT_ABI_VERSION",
            "SURFACE_META_ABI_VERSION",
            "TPX",
            "BIN_W",
            "MULTIFIDELITY_COMPACT_ABI_VERSION",
            "MULTIFIDELITY_COMPACT_RECEIVER_RECORD_WORDS",
        ] {
            let error = parse_experimental_defines(&format!("-D{name}=1")).unwrap_err();
            assert!(error.contains("generated by build.rs"), "{name}: {error}");
        }
    }

    #[test]
    fn non_define_options_unknown_names_and_split_defines_are_rejected() {
        for raw in [
            "-UARC_TRI_WALK",
            "@defines.rsp",
            "--compiler-options=-DV2_H0=0",
            "-D ARC_TRI_WALK=0",
            "-DUNKNOWN_SWITCH=1",
            "-DARC_TRI_WALK=",
            "-Darc_tri_walk=0",
            "-DONEPASS_NOMARCH=1",
            "-DONEPASS_NOMARCH_GROUND_DB=5.0",
        ] {
            assert!(
                parse_experimental_defines(raw).is_err(),
                "unexpectedly accepted `{raw}`"
            );
        }
    }

    #[test]
    fn z13_ladder_values_are_explicit_and_fail_closed() {
        for stride in ["4", "8", "16", "32"] {
            parse_experimental_defines(&format!(
                "-DMULTIFIDELITY_LINE -DMULTIFIDELITY_Z13_STRIDE={stride} -DMULTIFIDELITY_Z13_ADAPTIVE=0"
            ))
            .unwrap();
        }
        for raw in [
            "-DMULTIFIDELITY_Z13_STRIDE",
            "-DMULTIFIDELITY_Z13_STRIDE=2",
            "-DMULTIFIDELITY_Z13_STRIDE=64",
            "-DMULTIFIDELITY_Z13_ADAPTIVE",
            "-DMULTIFIDELITY_Z13_ADAPTIVE=1",
        ] {
            assert!(
                parse_experimental_defines(raw).is_err(),
                "unexpectedly accepted `{raw}`"
            );
        }
    }

    #[test]
    fn per_call_preclip_union_is_one_explicit_reviewed_arm() {
        assert_eq!(
            parse_experimental_defines("-DARC_UNION_BEFORE_SPAN_CLIP=1").unwrap(),
            ["-DARC_UNION_BEFORE_SPAN_CLIP=1"]
        );
        for raw in [
            "-DARC_UNION_BEFORE_SPAN_CLIP",
            "-DARC_UNION_BEFORE_SPAN_CLIP=0",
            "-DARC_UNION_BEFORE_SPAN_CLIP=2",
        ] {
            assert!(
                parse_experimental_defines(raw).is_err(),
                "unsafe per-call pre-clip union value unexpectedly accepted: `{raw}`"
            );
        }
    }

    #[test]
    fn duplicate_names_are_rejected_even_when_spellings_differ() {
        let error = parse_experimental_defines("-DARC_TRI_WALK -DARC_TRI_WALK=0").unwrap_err();
        assert!(error.contains("duplicate macro `ARC_TRI_WALK`"));
    }

    #[test]
    fn allowlist_and_generated_namespace_do_not_overlap() {
        assert!(REVIEWED_EXPERIMENTAL_DEFINES.is_sorted());
        assert!(REVIEWED_EXPERIMENTAL_DEFINES
            .iter()
            .all(|name| !is_build_generated_define(name)));
    }
}
