#!/usr/bin/env python3
"""Writes physics/src/doc29/approach_generated.rs: each noise class's final approach configuration
from the EASA ANP database (Doc 29 4th ed. Vol 2 B11): the landing flap of its anchor's DEFAULT
approach (the flap of its Land step), that flap's drag-to-lift ratio R with the gear down, the
height above the field from which the approach flies it (the first Descend step on it), and 90 %
of the maximum gross landing weight (the weight of ANP's default approaches).

usage: approach-configuration.py ANP_2_3_DIR ANP_V9_DIR OUT.rs  (needs openpyxl for the v9 workbooks)
"""
import csv, os, sys
import openpyxl

ANCHORS = [  # CLASS_NAMES order; None for the pinned classes (no thrust model)
    ("WING_FALLBACK", None), ("WING_A320", "A320-232"), ("WING_B738", "737800"), ("PROP_C172", "CNA172"),
    ("WING_B38M", "7378MAX"), ("WING_B789", "7878R"), ("WING_A21N", "A321-270N"),
    ("WING_A321", "A321-232"), ("WING_A20N", "A320-270N"), ("WING_A319", "A319-131"),
    ("FUSE_CRJ9", "CRJ9-ER"), ("WING_B748", "7478"), ("HELICOPTER", None), ("PROP_DH8D", "DHC830"),
    ("FUSE_C56X", "CIT3"), ("PROP_AT72", "ATR72"),
]


def rows_csv(directory, name):
    with open(os.path.join(directory, name), newline="", encoding="latin1") as handle:
        reader = csv.reader(handle, delimiter=";")
        header = next(reader)
        return [dict(zip(header, row)) for row in reader]


def rows_xlsx(directory, name):
    sheet = openpyxl.load_workbook(os.path.join(directory, name), read_only=True).worksheets[0]
    rows = sheet.iter_rows(values_only=True)
    header = next(rows)
    return [dict(zip(header, ["" if cell is None else str(cell) for cell in row])) for row in rows]


def main(anp, v9, out):
    aero = rows_csv(anp, "ANP2.3_Aerodynamic_coefficients.csv") + rows_xlsx(v9, "EASA_ANP_database_Aerodynamic_Coefficients_v9.xlsx")
    steps = rows_csv(anp, "ANP2.3_Default_approach_procedural_steps.csv") + rows_xlsx(v9, "EASA_ANP_database_Default_Approach_Procedural_Steps_v9.xlsx")
    aircraft = rows_csv(anp, "ANP2.3_Aircraft.csv") + rows_xlsx(v9, "EASA_ANP_database_Aircraft_v9.xlsx")
    lines = []
    for class_name, anchor in ANCHORS:
        if anchor is None:
            lines.append(f'    ApproachConfiguration::none("{class_name}"),')
            continue
        own = [s for s in steps if s["ACFT_ID"] == anchor]
        profile = sorted({s["Profile_ID"] for s in own})[0]  # DEFAULT, or v9's DEFAULT1
        own = sorted((s for s in own if s["Profile_ID"] == profile), key=lambda s: float(s["Step Number"]))
        flap = next(s["Flap_ID"] for s in own if s["Step Type"] == "Land")
        start = next(float(s["Start Altitude(ft)"]) for s in own if s["Step Type"] == "Descend" and s["Flap_ID"] == flap)
        drag = next(float(a["R"]) for a in aero if a["ACFT_ID"] == anchor and a["Op Type"] == "A" and a["Flap_ID"] == flap)
        landing = next(float(a["Max Gross Landing Weight (lb)"]) for a in aircraft if a["ACFT_ID"] == anchor)
        lines.append(
            f'    ApproachConfiguration {{ class_name: "{class_name}", anchor: "{anchor}/{profile}", '
            f'flap: "{flap}", drag_ratio: {drag}, from_ft_afe: {start}, landing_weight_lb: {round(0.9 * landing, 1)} }},'
        )
    text = f"""//! Generated by `scripts/approach-configuration.py` from the EASA ANP database v2.3 and v9 (Doc 29
//! 4th ed. Vol 2 B11): per noise class, the landing flap of its anchor's DEFAULT approach, that
//! flap's drag-to-lift ratio R with the gear down, the height above the field from which the
//! approach flies it, and 90 % of the maximum gross landing weight. Not edited by hand.

use super::profiles_generated::NUM_CLASSES;
use super::thrust::ApproachConfiguration;

/// Per-noise-class final approach configuration, in CLASS_NAMES order.
pub static APPROACH: [ApproachConfiguration; NUM_CLASSES] = [
{chr(10).join(lines)}
];
"""
    with open(out, "w") as handle:
        handle.write(text)


if __name__ == "__main__":
    main(*sys.argv[1:4])
