#!/usr/bin/env python3
"""Writes physics/src/doc29/spectra_generated.rs: per noise class, the unweighted 1/3-octave spectra
(50 Hz - 10 kHz) of its anchor's approach and departure spectral classes in the EASA ANP database,
at 305 m (1,000 ft) in the SAE AIR-1845 atmosphere the NPD curves are normalised to (Doc 29 4th ed.
Vol 2 Appendix D). Classes without an ANP anchor (helicopters) have none.

usage: spectral-classes.py ANP_2_3_DIR ANP_V9_DIR OUT.rs  (needs openpyxl for the v9 workbooks)
"""
import csv, os, sys
import openpyxl

ANCHORS = [  # CLASS_NAMES order: the ANP aircraft whose spectral classes the class takes
    ("WING_FALLBACK", "737800"), ("WING_A320", "A320-232"), ("WING_B738", "737800"),
    ("PROP_C172", "CNA172"), ("WING_B38M", "7378MAX"), ("WING_B789", "7878R"),
    ("WING_A21N", "A321-270N"), ("WING_A321", "A321-232"), ("WING_A20N", "A320-270N"),
    ("WING_A319", "A319-131"), ("FUSE_CRJ9", "CL601"), ("WING_B748", "7478"),
    ("HELICOPTER", None), ("PROP_DH8D", "DHC830"), ("FUSE_C56X", "CIT3"),
]


def rows_csv(directory, name):
    with open(os.path.join(directory, name), newline="", encoding="latin1") as handle:
        reader = csv.reader(handle, delimiter=";")
        header = next(reader)
        return [dict(zip(header, row)) for row in reader]


def rows_xlsx(directory, name):
    sheet = openpyxl.load_workbook(os.path.join(directory, name), read_only=True).worksheets[0]
    rows = sheet.iter_rows(values_only=True)
    header = [str(cell).strip() if cell is not None else "" for cell in next(rows)]
    return [dict(zip(header, ["" if cell is None else str(cell).strip() for cell in row])) for row in rows]


def main(anp, v9, out):
    aircraft = rows_xlsx(v9, "EASA_ANP_database_Aircraft_v9.xlsx") + rows_csv(anp, "ANP2.3_Aircraft.csv")
    classes = {row["Spectral Class ID"]: row for row in rows_xlsx(v9, "EASA_ANP_database_Spectral_Classes_v9.xlsx")}
    bands = [key for key in next(iter(classes.values())) if key.startswith("L_")]
    assert len(bands) == 24, bands
    lines = []
    for class_name, anchor in ANCHORS:
        if anchor is None:
            lines.append("    None,")
            continue
        row = next(a for a in aircraft if a["ACFT_ID"] == anchor)
        approach_id = str(int(float(row["Approach Spectral Class ID"])))
        departure_id = str(int(float(row["Departure Spectral Class ID"])))
        spectrum = lambda cid: ", ".join(repr(float(classes[cid][band])) for band in bands)
        lines.append(
            f'    Some(ClassSpectra {{ class_name: "{class_name}", anchor: "{anchor}", '
            f"approach_class: {approach_id}, departure_class: {departure_id},\n"
            f"        approach_db: [{spectrum(approach_id)}],\n"
            f"        departure_db: [{spectrum(departure_id)}] }}),"
        )
    text = f"""//! Generated by `scripts/spectral-classes.py` from the EASA ANP database (v9 spectral classes and
//! aircraft, v2.3 aircraft): per noise class the unweighted 1/3-octave spectra (50 Hz - 10 kHz) of
//! its anchor's approach and departure spectral classes at 305 m in the SAE AIR-1845 atmosphere
//! (Doc 29 4th ed. Vol 2 Appendix D). Not edited by hand.

use super::atmosphere::ClassSpectra;
use super::profiles_generated::NUM_CLASSES;

/// Per-noise-class spectra, in CLASS_NAMES order (none for the helicopter class).
pub static SPECTRA: [Option<ClassSpectra>; NUM_CLASSES] = [
{chr(10).join(lines)}
];
"""
    with open(out, "w") as handle:
        handle.write(text)


if __name__ == "__main__":
    main(*sys.argv[1:4])
