[package]
name = "paint"
version = "0.1.0"
edition.workspace = true
publish.workspace = true


[dependencies]
tiles = { path = "../tiles" }
physics = { path = "../physics" }
popup = { path = "../popup" }
rayon = "1.12"
brotli = "8"
pmtiles = { version = "0.23.0", default-features = false, features = ["write"] }
serde_json = "1"
