import type { NoiseComputeData, SegmentTrace, SegmentTracesSummary } from '../src/types/noise'
import { popupFixture } from './support'

export function screeningFanPopupFixture(lat: number, lng: number): NoiseComputeData {
  const segment: SegmentTrace = {
    kind: 'road',
    osm_id: 42,
    segment_idx: 3,
    name: 'Fan fixture road',
    subtype: 'secondary',
    is_dominant_of_group: true,
    start_lat: lat - 0.0018,
    start_lon: lng - 0.00175,
    end_lat: lat - 0.0018,
    end_lon: lng + 0.00175,
    cp_lat: lat - 0.0018,
    cp_lon: lng,
    length_m: 250,
    dist_m: 200,
    d_slant_m: 200,
    bridge: false,
    tunnel: false,
    emission: {
      kind: 'road',
      aadt_light: 12_000,
      aadt_medium: 600,
      aadt_heavy: 900,
      aadt_moto: 300,
      speed_kmh: 80,
      surface_corr_db: 0,
      surface: 'asphalt',
      traffic_source: 'default_by_class',
      dataset_id: 0,
      provenance: null,
      road_class: 'secondary',
      bridge: false,
      tunnel: false,
      oneway: false,
      lanes: 2,
    },
    propagation: {
      model: 'cnossos',
      baseline: {
        geometric_db: 31,
        atmospheric_bands: [0.01, 0.02, 0.04, 0.08, 0.16, 0.32, 0.64, 1.28],
        ground_factor_g: 0.5,
        source_height_m: 0.05,
        finite_line_corr_db: -1.2,
        reflection_boost_db: 0,
      },
      path_profile: {
        t: [0, 0.5, 1],
        elevation_m: [350, 350, 350],
        forest_u8: [0, 0, 0],
        imd_u8: [50, 50, 50],
        dist_m: 200,
        step_m_med: 100,
        src_lat: lat - 0.0018,
        src_lon: lng,
        rcv_lat: lat,
        rcv_lon: lng,
        src_alt_m: 350.05,
        rcv_alt_m: 354,
      },
      terrain: {
        delta_m: 0,
        attenuation_bands: [0, 0, 0, 0, 0, 0, 0, 0],
        edges: [],
        delta_star_m: 0,
      },
      screening: {
        attenuation_bands: [0.8, 1.1, 1.5, 2, 2.7, 3.4, 4.1, 4.8],
        obstacle: {
          delta_m: 0.1,
          step_m: 100,
          edge: {
            kind: 'building',
            t: 0.5,
            height_m: 8,
            screen_h_m: 5,
            obstacle_id: 7,
          },
        },
        fan: {
          span_deg: 50,
          blocked_fraction: 0.22,
          quadrature: 'arc',
          intervals: [
            { from_deg: -25, to_deg: -8, blocked: false, terrain_db: 0, screen_db: 0, contains_cp: false },
            {
              from_deg: -8,
              to_deg: -3,
              blocked: true,
              obstacle: { kind: 'barrier', height_m: 3.5 },
              terrain_db: 1.3,
              screen_db: 7.2,
              contains_cp: false,
            },
            {
              from_deg: -3,
              to_deg: 3,
              blocked: true,
              obstacle: { kind: 'building', height_m: 8 },
              terrain_db: 0,
              screen_db: 10.4,
              contains_cp: true,
            },
            { from_deg: 3, to_deg: 14, blocked: false, terrain_db: 0, screen_db: 0, contains_cp: false },
            { from_deg: 14, to_deg: 25, blocked: false, terrain_db: 0, screen_db: 0, contains_cp: false },
          ],
        },
      },
      vegetation: {
        forest_depth_m: 0,
        sampled_path_m: 200,
        attenuation_bands: [0, 0, 0, 0, 0, 0, 0, 0],
        forest_runs: [],
      },
      ground: {
        factor_g: 0.5,
        attenuation_bands: [0, 0, 0, 0, 0, 0, 0, 0],
      },
      lw_bands: {
        day: [70, 71, 72, 73, 74, 75, 76, 77],
        evening: [69, 70, 71, 72, 73, 74, 75, 76],
        night: [67, 68, 69, 70, 71, 72, 73, 74],
      },
      lw_db_a: { day: 80, evening: 79, night: 77 },
      received_bands: {
        day: [45, 46, 47, 48, 49, 50, 51, 52],
        evening: [44, 45, 46, 47, 48, 49, 50, 51],
        night: [42, 43, 44, 45, 46, 47, 48, 49],
      },
    },
    received_lden: {
      full: 58.5,
      free_field: 62,
      no_terrain: 58.5,
      no_screening: 60.3,
      no_vegetation: 58.5,
      no_ground: 58.1,
      no_atmospheric: 58.8,
    },
  }
  const meta: SegmentTracesSummary = {
    total_count: 1,
    truncated: false,
    road_count: 1,
    railway_count: 0,
    aircraft_ground_count: 0,
    aircraft_airborne_count: 0,
    aircraft_cruise_count: 0,
    building_count: 0,
    industrial_count: 0,
    road_total: 1,
    railway_total: 0,
    aircraft_ground_total: 0,
    aircraft_airborne_total: 0,
    aircraft_cruise_total: 0,
    building_total: 0,
    industrial_total: 0,
  }
  return {
    ...popupFixture(lat, lng, 58.5, { road: 58.5 }),
    segments: [segment],
    segments_meta: meta,
  }
}
