//! Generated by `scripts/approach-configuration.py` from the EASA ANP database v2.3 and v9 (Doc 29
//! 4th ed. Vol 2 B11): per noise class, the landing flap of its anchor's DEFAULT approach, that
//! flap's drag-to-lift ratio R with the gear down, the height above the field from which the
//! approach flies it, and 90 % of the maximum gross landing weight. Not edited by hand.

use super::profiles_generated::NUM_CLASSES;
use super::thrust::ApproachConfiguration;

/// Per-noise-class final approach configuration, in CLASS_NAMES order.
pub static APPROACH: [ApproachConfiguration; NUM_CLASSES] = [
    ApproachConfiguration::none("WING_FALLBACK"),
    ApproachConfiguration {
        class_name: "WING_A320",
        anchor: "A320-232/DEFAULT",
        flap: "FULL_D",
        drag_ratio: 0.121141,
        from_ft_afe: 1819.0,
        landing_weight_lb: 130954.5,
    },
    ApproachConfiguration {
        class_name: "WING_B738",
        anchor: "737800/DEFAULT",
        flap: "A_30",
        drag_ratio: 0.117166,
        from_ft_afe: 2817.0,
        landing_weight_lb: 131670.0,
    },
    ApproachConfiguration {
        class_name: "PROP_C172",
        anchor: "CNA172/DEFAULT",
        flap: "10-D",
        drag_ratio: 0.0994,
        from_ft_afe: 1000.0,
        landing_weight_lb: 2205.0,
    },
    ApproachConfiguration {
        class_name: "WING_B38M",
        anchor: "7378MAX/DEFAULT",
        flap: "A_30",
        drag_ratio: 0.116638,
        from_ft_afe: 2817.0,
        landing_weight_lb: 137520.0,
    },
    ApproachConfiguration {
        class_name: "WING_B789",
        anchor: "7878R/DEFAULT",
        flap: "FLAP30",
        drag_ratio: 0.105,
        from_ft_afe: 2725.0,
        landing_weight_lb: 342000.0,
    },
    ApproachConfiguration {
        class_name: "WING_A21N",
        anchor: "A321-270N/DEFAULT1",
        flap: "AFULLD",
        drag_ratio: 0.132295,
        from_ft_afe: 1813.4,
        landing_weight_lb: 157145.4,
    },
    ApproachConfiguration {
        class_name: "WING_A321",
        anchor: "A321-232/DEFAULT",
        flap: "FULL_D",
        drag_ratio: 0.119073,
        from_ft_afe: 2003.0,
        landing_weight_lb: 149804.1,
    },
    ApproachConfiguration {
        class_name: "WING_A20N",
        anchor: "A320-270N/DEFAULT1",
        flap: "A_FULL_D",
        drag_ratio: 0.119306,
        from_ft_afe: 1733.0,
        landing_weight_lb: 133731.9,
    },
    ApproachConfiguration {
        class_name: "WING_A319",
        anchor: "A319-131/DEFAULT",
        flap: "FULL_D",
        drag_ratio: 0.124534,
        from_ft_afe: 1971.0,
        landing_weight_lb: 124010.1,
    },
    ApproachConfiguration {
        class_name: "FUSE_CRJ9",
        anchor: "CRJ9-ER/DEFAULT",
        flap: "D-45",
        drag_ratio: 0.1551,
        from_ft_afe: 1000.0,
        landing_weight_lb: 66150.0,
    },
    ApproachConfiguration {
        class_name: "WING_B748",
        anchor: "7478/DEFAULT",
        flap: "F_30",
        drag_ratio: 0.143406,
        from_ft_afe: 3000.0,
        landing_weight_lb: 681300.0,
    },
    ApproachConfiguration::none("HELICOPTER"),
    ApproachConfiguration {
        class_name: "PROP_DH8D",
        anchor: "DHC830/DEFAULT",
        flap: "D-35",
        drag_ratio: 0.103483,
        from_ft_afe: 1000.0,
        landing_weight_lb: 37800.0,
    },
    ApproachConfiguration {
        class_name: "FUSE_C56X",
        anchor: "CIT3/DEFAULT",
        flap: "D-40",
        drag_ratio: 0.147159,
        from_ft_afe: 1000.0,
        landing_weight_lb: 15300.0,
    },
    ApproachConfiguration {
        class_name: "PROP_AT72",
        anchor: "ATR72/DEFAULT",
        flap: "33-A-G",
        drag_ratio: 0.105,
        from_ft_afe: 2802.0,
        landing_weight_lb: 44343.0,
    },
];
